### ISSUE TITLE
Table name with "-" fire exception - should send error message at backend

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1019]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
## My environment is:

(Please fill in the actual values from your environment)

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | 5.6 |  |
| Contao version: | 3.5.12 |  |
| MetaModels version: | a11 |  |
| Installation via composer | yes |  |
| Installed MetaModels packages | bundle_all |  |
## Issue description
- save table name with character "-"
## Steps to reproduce
1. add new MM
2. name e,g, "test-2"
3. save
## Describe the behaviour of the application

Error:

```
Fatal error: Uncaught exception Exception with message Der Tabellenname "mm_test-2" ist ungültig. thrown in composer\vendor\metamodels\core\src\MetaModels\Helper\TableManipulation.php on line 224

#0 composer\vendor\metamodels\core\src\MetaModels\Helper\TableManipulation.php(291): MetaModels\Helper\TableManipulation::checkTablename('mm_test-2')
#1 composer\vendor\metamodels\core\src\MetaModels\Helper\TableManipulation.php(308): MetaModels\Helper\TableManipulation::checkTableDoesNotExist('mm_test-2')
#2 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber.php(525): MetaModels\Helper\TableManipulation::createTable('mm_test-2')
#3 [internal function]: MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber->handleUpdate(Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(301): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(631): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->handlePostPersist()
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(723): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(599): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(574): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(140): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#19 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#20 contao\main.php(20): Contao\BackendMain->run()
#21 {main}
```

btw: look at http://dev.mysql.com/doc/refman/5.5/en/identifiers.html and compare with https://github.com/MetaModels/core/blob/master/src/MetaModels/Helper/TableManipulation.php#L163-L168 - we can start with digit and can use $

**Comment by discordier** [comment]
According to the MySQL manual a dash is still illegal (as it will get parsed as equation).

The exception however must get properly caught.

**Comment by zonky2** [comment]
o.k. - correct objection, the dash is not legal... thanks

**Comment by discordier** [comment]
I can not reproduce this. I always get the correct error message shown as the exception is captured.

**Comment by zonky2** [comment]
is fixed ... irgendwann ;-
