### ISSUE TITLE
Error if delete atribute - dependet at existing render setting pid

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1044]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
## My environment is:

(Please fill in the actual values from your environment)

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | 5.6 |  |
| Contao version: | 3.5.17 |  |
| MetaModels version: | alpha14 |  |
| Installation via composer: | yes |  |
| Installed MetaModels packages: | bundle_all |  |
| DCG version: | beta38 |  |
## Issue description

error if we delete attribute

```
Fatal error: Uncaught exception InvalidArgumentException with message Could not retrieve MetaModel 7 thrown in composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\Attribute\Subscriber.php on line 480 
#0 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\Attribute\Subscriber.php(539): MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->createAttributeInstance(Array)
#1 [internal function]: MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->handleDeleteAttribute(Object(ContaoCommunityAlliance\DcGeneral\Event\PreDeleteModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PreDeleteModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PreDeleteModelEvent))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler.php(230): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PreDeleteModelEvent))
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler.php(163): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler->deepDelete(Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler->process()
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler.php(71): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#14 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#15 contao\main.php(20): Contao\BackendMain->run()
#16 {main}
```
## Steps to reproduce
1. create attribute
2. create different render settings - more than exusted metamodels
3. load attribte at render settings
4. delete attribute

**Comment by zonky2** [comment]
Fixed with DCG beta39
