### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() mm_attr_tabletext.text on line 2

### ISSUE THREAD

**Issue by akroii** [MetaModels/core#1084]
I confirm that:
- [x ] I have tested this with the latest version available
- [x ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
- [x] I have checked the Contao community forums for references https://community.contao.org/

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |5.5.9-1ubuntu4.4|                                  |
| Contao version:                     |3.5.21|                                  |
| MetaModels version:                 |2.0.0|                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |bundle_all|                                  |
| DCG version:                        |?|installed, but version not visible in composer|

## Issue description

My error.log is full of:
```
[04-Feb-2017 19:16:57 Europe/Berlin]
PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/metamodelsattribute_tabletext/templates/mm_attr_tabletext.text on line 2
#0 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/metamodelsattribute_tabletext/templates/mm_attr_tabletext.text(2): __error(2, 'Invalid argumen...', '/var/www/vhosts...', 2, Array)
#1 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Render/Template.php(300): include('/var/www/vhosts...')
#2 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Attribute/Base.php(515): MetaModels\Render\Template->parse('text', true)
#3 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Item.php(113): MetaModels\Attribute\Base->parseValue(Array, 'html5', Object(MetaModels\Render\Setting\Simple))
#4 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Item.php(405): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\TableText\TableText), 'html5', Object(MetaModels\Render\Setting\Collection))
#5 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Items.php(254): MetaModels\Item->parseValue('html5', Object(MetaModels\Render\Setting\Collection))
#6 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/Items.php(270): MetaModels\Items->parseValue('html5', Object(MetaModels\Render\Setting\Collection))
#7 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/ItemList.php(804): MetaModels\Items->parseAll('html5', Object(MetaModels\Render\Setting\Collection))
#8 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(115): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#9 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/classes/Hybrid.php(239): MetaModels\FrontendIntegration\HybridList->compile()
#10 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#11 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#12 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/elements/ContentModule.php(59): MetaModels\FrontendIntegration\HybridList->generate()
#13 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#14 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#15 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#16 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#18 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 /var/www/vhosts/xxxxxx.de/httpdocs/contaov123/index.php(20): Contao\FrontendIndex->run()
#22 {main}
```
## Steps to reproduce
1. [https://community.contao.org/de/showthread.php?56878-Attribut-quot-Text-table-quot-Invalid-argument-supplied-for-foreach()](https://community.contao.org/de/showthread.php?56878-Attribut-quot-Text-table-quot-Invalid-argument-supplied-for-foreach())
2. Setting up a Render-Setting of a MM -> Attributesettings -> Set 'tabletext' -> leave unfulfilled template setting
(it is not important to set up an alternative template.. the error message occurs randomly without any schema) -> i'am not able to reproduce

mm_attr_tabletext.html5:
(but it is not used in rendersettings-> see above(steps to reproducs: 2)):
the error message occurs even when i delete this file and unset the alternative template settings in the rendersettings
```
<table class="tabletext<?php echo $this->additional_class; ?>">
	<?php foreach ($this->raw as $k => $row) : ?><tr>
		<?php foreach ($row as $kk =>$col): ?><td><?php echo $col['value']; ?></td><?php endforeach; ?>
	</tr><?php endforeach;?>
</table>

```

metamodel_prerendered_detail.html5:
```
[...]
 <div class="tabletext<?php echo $this->additional_class; ?>">
                                <?php if (is_array($k) || is_object($k)):?>
                                    <?php foreach ($arrItem['raw']['naehrwerte'] as $k => $row) : ?>
                                        <div class="row">
                                            <?php
                                                foreach ($row as $kk => $col): ?>
                                                <div class="col-xs-6">
                                                    <p><?php echo $col['value']; ?></p>
                                                </div>
                                                <?php endforeach; ?>
                                        </div>
                                    <?php endforeach;?>
                                <?php endif;?>
                            </div>
```

## Describe the behaviour of the application

Error logs will be filled, when the metamodel_prerendered_detail.html5 (on product page) is called.

## Describe the expected behaviour of the application

My error log should not be filled with lines of with 100000 error messages ;)

## Screenshots

<img width="698" alt="bildschirmfoto 2017-02-04 um 21 27 24 kopie" src="https://cloud.githubusercontent.com/assets/8830861/22621304/e114fea8-eb20-11e6-86af-deaed1718c59.png">

**Comment by zonky2** [comment]
pls follow https://github.com/MetaModels/attribute_tabletext/pull/21
