### ISSUE TITLE
FR: Item persister and retriever

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1097]
Check https://github.com/MetaModels/core/tree/feature/item-persister-and-retriever

**Comment by zonky2** [comment]
dev-feature/item-persister-and-retriever (b63bd7e3)

Update and save item at BE:

```
Warning: sprintf(): Too few arguments in composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php on line 218

#0 [internal function]: __error(2, 'sprintf(): Too ...', 'C:\\Contao2Go\\ht...', 218, Array)
#1 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(218): sprintf('UPDATE %1$s %%s...', 'mm_mitarbeiterl...', '?')
#2 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(99): MetaModels\DataAccess\ItemPersister->saveRawColumns(Array, Array)
#3 composer\vendor\metamodels\core\src\MetaModels\MetaModel.php(429): MetaModels\DataAccess\ItemPersister->saveItem(Object(MetaModels\Item))
#4 composer\vendor\metamodels\core\src\MetaModels\Item.php(324): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Data\Driver.php(582): MetaModels\Item->save()
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(630): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(725): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#15 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#16 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#17 contao\main.php(20): Contao\BackendMain->run()
#18 {main}


Fatal error: Uncaught exception Exception with message Empty query string thrown in system\modules\core\library\Contao\Database\Statement.php on line 145

#0 system\modules\core\library\Contao\Database.php(181): Contao\Database\Statement->prepare(false)
#1 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(219): Contao\Database->prepare(false)
#2 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(99): MetaModels\DataAccess\ItemPersister->saveRawColumns(Array, Array)
#3 composer\vendor\metamodels\core\src\MetaModels\MetaModel.php(429): MetaModels\DataAccess\ItemPersister->saveItem(Object(MetaModels\Item))
#4 composer\vendor\metamodels\core\src\MetaModels\Item.php(324): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Data\Driver.php(582): MetaModels\Item->save()
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(630): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(725): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#15 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#16 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#17 contao\main.php(20): Contao\BackendMain->run()
#18 {main}
```

**Comment by zonky2** [comment]
published/unpublished per "green eye" doesn´t works - Ajax send same error as https://github.com/MetaModels/core/issues/1097#issuecomment-287287706

**Comment by zonky2** [comment]
after MM uptate:

Update or New and save item at BE:

```Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system\modules\core\library\Contao\Database\Statement.php on line 331

#0 system\modules\core\library\Contao\Database\Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#1 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(221): Contao\Database\Statement->execute(Array)
#2 composer\vendor\metamodels\core\src\MetaModels\DataAccess\ItemPersister.php(99): MetaModels\DataAccess\ItemPersister->saveRawColumns(Array, Array)
#3 composer\vendor\metamodels\core\src\MetaModels\MetaModel.php(429): MetaModels\DataAccess\ItemPersister->saveItem(Object(MetaModels\Item))
#4 composer\vendor\metamodels\core\src\MetaModels\Item.php(324): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Data\Driver.php(582): MetaModels\Item->save()
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(630): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(725): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#15 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#16 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#17 contao\main.php(20): Contao\BackendMain->run()
#18 {main}
```

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/blob/feature/item-persister-and-retriever/src/MetaModels/DataAccess/ItemPersister.php#L215

```diff
-                    'UPDATE %1$s %%s=? WHERE id IN (%2$s)',
+                    'UPDATE %1$s %%s WHERE id IN (%2$s)',
```

**Comment by zonky2** [comment]
it´s not possible to work with variants
* parent override all variant values at childs at save
* https://github.com/MetaModels/core/blob/feature/item-persister-and-retriever/src/MetaModels/DataAccess/ItemPersister.php#L108
```diff
-$variantIds = [];
+$variantIds = [$itemId];

**Comment by zonky2** [comment]
@discordier have you a new strategy for vatiants?

**Comment by discordier** [comment]
Not yet, however we should implement it in here.

**Comment by discordier** [comment]
please follow ups to #1112
