### ISSUE TITLE
Entrymask Settings - Error on loading the InputScreen BE 

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/core#1105]
## Environment

PHP7
Contao 3.5.16
MetaModels/core alpha15
No translated attributes
DcGeneral beta39

https://github.com/MetaModels/core/blob/hotfix/alpha-15/src/MetaModels/DcGeneral/Events/Table/InputScreens/Subscriber.php

## Maybe the bug is here ? (disable this listener hides the error)
```
->addListener(
                BuildWidgetEvent::NAME,
                array($this, 'buildMandatoryWidget')
            )
```

## ERROR

````
Fatal error: Uncaught exception Error with message Call to a member function getAttributeById() on null thrown in system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/InputScreens/Subscriber.php on line 362
#0 [internal function]: MetaModels\DcGeneral\Events\Table\InputScreens\Subscriber->buildMandatoryWidget(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#3 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(335): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('mandatory', NULL)
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(474): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->renderWidget('mandatory', false, NULL)
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(813): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#15 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#16 contao/main.php(20): Contao\BackendMain->run()
#17 {main}`
```

**Comment by MoniqueHahnefeld** [comment]
strange. i tested it again now and it is away.... omg, maybe cache or something else
