### ISSUE TITLE
FTP - Installation not possible 

### ISSUE THREAD

**Issue by Messa1** [MetaModels/core#1108]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |   5.6.30 / 128M       |                                  |
| Contao version:                     |   3.5.24       |                                  |
| MetaModels version:                 |    Nightly      |                                  |
| Installation via composer:          | (yes/no) |        NO                          |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

Installation via FTP not possible - DB error
Check also my post here.
https://community.contao.org/de/showthread.php?66395-Installation-nicht-m%C3%B6glich&p=437618#post437618

## Steps to reproduce

1.  Download Nightly
2. Upload FTP
3. Try to create tables over install.php

## Describe the behaviour of the application

Error :) 

```
Fatal error: Query error: Table 'contao.tl_metamodel_attribute' doesn't exist (SELECT metamodel.tableName, attribute.colname FROM tl_metamodel_attribute AS attribute LEFT JOIN tl_metamodel AS metamodel ON (metamodel.id=attribute.pid) WHERE attribute.type='timestamp')
#0 /DOMAIN.com/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /DOMAIN.com/system/modules/metamodelsattribute_timestamp/classes/src/MetaModels/Attribute/Timestamp/Helper/UpgradeHandler.php(79): Contao\Database\Statement->execute('timestamp')
#2 /DOMAIN.com/system/modules/metamodelsattribute_timestamp/classes/src/MetaModels/Attribute/Timestamp/Helper/UpgradeHandler.php(55): MetaModels\Attribute\Timestamp\Helper\UpgradeHandler->ensureCorrectColumnType()
#3 /DOMAIN.com/system/modules/!metamodels-tng-branch/config/runonce_1.php(25): MetaModels\Attribute\Timestamp\Helper\UpgradeHandler->perform()
#4 /DOMAIN.com/system/modules/!metamodels-tng-branch/config/runonce.php(14): require_once('/home/recenmbt/...')
#5 /DOMAIN.com/system/modules/!metamodels-tng-branch/config/runonce.php(36): runonce_f9467bbca9cbfa38d987eee4638796a8->run()
#6 /DOMAIN.com/system/modules/core/classes/Backend.php(273): include('/home/recenmbt/...')
#7 /DOMAIN.com/system/modules/core/controllers/BackendInstall.php(628): Contao\Backend->handleRunOnce() #8 /DOMAIN.com/system/modules/core/controllers/BackendInstall.php(177): Contao\BackendInstall->adjustDatabaseTables()
#9 /DOMAIN.com/contao/install.php(24): Contao\BackendInstall->run()
#10 {main} in system/modules/!metamodels-tng-branch/config/runonce.php on line 22
```

```
#0 [internal function]: __error(256, 'Query error: Ta...', '/home/domain/...', 22, Array)
#1 system/modules/!metamodels-tng-branch/config/runonce.php(22): trigger_error('Query error: Ta...', 256)
#2 system/modules/!metamodels-tng-branch/config/runonce.php(36): runonce_f9467bbca9cbfa38d987eee4638796a8->run()
#3 system/modules/core/classes/Backend.php(273): include('/home/domain/...')
#4 system/modules/core/controllers/BackendInstall.php(628): Contao\Backend->handleRunOnce()
#5 system/modules/core/controllers/BackendInstall.php(177): Contao\BackendInstall->adjustDatabaseTables()
#6 contao/install.php(24): Contao\BackendInstall->run()
#7 {main}

```

```
Name                                             Version       Last modification
========================================================================================
http://c-c-a.org/
contao-community-alliance/dc-general             2.0.0-beta38  2016-08-23T13:32:18+00:00
contao-community-alliance/dependency-container   1.8.3         2015-12-08T01:53:46+00:00
contao-community-alliance/event-dispatcher       1.3.0         2014-11-28T14:49:55+00:00
contao-community-alliance/events-contao-bindings 3.5.1         2016-05-04T08:26:41+00:00
contao-community-alliance/translator             2.0.2         2015-11-25T18:42:08+00:00
----------------------------------------------------------------------------------------

http://bit3.de
contao-community-alliance/meta-palettes          1.10.0        2016-10-26T06:51:58+00:00
----------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                       1.0.0         2015-10-27T02:38:03+00:00
----------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                   v1.5.4        2015-12-19T05:03:47+00:00
----------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                    1.0.2         2014-02-07T22:35:55+00:00
----------------------------------------------------------------------------------------

http://www.minifier.org
matthiasmullie/minify                            1.3.44        2017-03-16T16:42:50+00:00
----------------------------------------------------------------------------------------

http://github.com/matthiasmullie/path-converter
matthiasmullie/path-converter                    1.1.0         2017-01-26T08:54:49+00:00
----------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard               3.3.10        2017-02-27T17:54:10+00:00
----------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                       2.0.0         2016-05-03T22:07:57+00:00
metamodels/attribute_checkbox                    2.0.1         2017-01-12T03:35:57+00:00
metamodels/attribute_combinedvalues              2.0.1         2017-03-06T19:35:43+00:00
metamodels/attribute_country                     2.0.0         2016-05-30T19:41:08+00:00
metamodels/attribute_decimal                     2.0.0         2016-05-09T15:28:30+00:00
metamodels/attribute_file                        2.0.0         2016-05-30T16:39:30+00:00
metamodels/attribute_langcode                    2.0.0         2016-12-07T06:41:50+00:00
metamodels/attribute_longtext                    2.0.0         2017-01-12T04:14:51+00:00
metamodels/attribute_numeric                     2.0.0         2017-01-12T04:54:18+00:00
metamodels/attribute_rating                      2.0.0         2017-02-28T01:18:52+00:00
metamodels/attribute_select                      2.0.0         2017-02-22T21:36:14+00:00
metamodels/attribute_tabletext                   2.0.0         2017-02-07T00:06:43+00:00
metamodels/attribute_tags                        2.0.0         2017-02-27T23:31:19+00:00
metamodels/attribute_text                        2.0.0         2017-02-28T00:05:33+00:00
metamodels/attribute_timestamp                   2.0.1         2017-01-16T10:15:26+00:00
metamodels/attribute_translatedalias             2.0.0         2017-01-12T01:50:38+00:00
metamodels/attribute_translatedcheckbox          2.0.0         2016-05-04T10:03:08+00:00
metamodels/attribute_translatedcombinedvalues    2.0.0         2017-02-07T01:54:26+00:00
metamodels/attribute_translatedfile              2.0.0         2017-02-28T09:13:40+00:00
metamodels/attribute_translatedlongtext          2.0.0         2017-02-07T00:58:51+00:00
metamodels/attribute_translatedselect            2.0.0         2017-02-07T01:40:21+00:00
metamodels/attribute_translatedtabletext         2.0.1         2017-03-08T20:36:21+00:00
metamodels/attribute_translatedtags              2.0.0         2017-02-27T23:42:42+00:00
metamodels/attribute_translatedtext              2.0.0         2016-12-08T17:31:54+00:00
metamodels/attribute_translatedurl               2.0.0         2017-02-07T02:25:07+00:00
metamodels/attribute_url                         2.0.1         2016-09-27T19:34:47+00:00
metamodels/bundle_all                            2.0.0         2015-11-11T21:55:59+00:00
metamodels/bundle_attributes                     2.0.1         2016-05-04T09:37:14+00:00
metamodels/bundle_filter                         2.0.0         2015-11-11T21:01:14+00:00
metamodels/bundle_nontranslated                  2.0.1         2016-05-04T09:23:22+00:00
metamodels/bundle_translated                     2.0.1         2016-05-04T09:11:51+00:00
metamodels/core                                  2.0.0-alpha14 2016-08-24T16:27:48+00:00
metamodels/filter_checkbox                       2.0.0         2016-05-30T21:54:34+00:00
metamodels/filter_fromto                         2.0.0         2016-05-30T22:28:20+00:00
metamodels/filter_range                          2.0.0         2016-05-30T22:55:02+00:00
metamodels/filter_select                         2.0.0         2017-01-10T22:19:55+00:00
metamodels/filter_tags                           2.0.0         2017-02-14T21:08:49+00:00
metamodels/filter_text                           2.0.1         2017-03-08T23:22:24+00:00
----------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                    v1.1.1        2013-11-22T08:30:29+00:00
----------------------------------------------------------------------------------------

https://symfony.com
symfony/event-dispatcher                         v2.8.19       2017-04-03T20:37:06+00:00
symfony/expression-language                      v2.8.19       2017-04-03T23:11:44+00:00
----------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder            1.1.3         2015-12-23T16:50:06+00:00
```

**Comment by discordier** [comment]
Follow up to MetaModels/attribute_timestamp#28
