### ISSUE TITLE
Error at FE at CE-MM-List and FE-Filter if MM deleted

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1152]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     5.6     |                                  |
| Contao version:                     |   3.5.17       |                                  |
| MetaModels version:                 |    core-a15      |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |    b39      |                                  |

## Issue description
Filter:
```
Fatal error: Uncaught exception RuntimeException with message Error: Filter setting 0 not attached to a MetaModel thrown in composer\vendor\metamodels\core\src\MetaModels\Filter\Setting\Collection.php on line 102

#0 composer\vendor\metamodels\core\src\MetaModels\Filter\Setting\Collection.php(196): MetaModels\Filter\Setting\Collection->getMetaModel()
#1 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\FrontendFilter.php(293): MetaModels\Filter\Setting\Collection->getParameterFilterWidgets(Array, Array, Object(MetaModels\FrontendIntegration\FrontendFilterOptions))
#2 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\FrontendFilter.php(79): MetaModels\FrontendIntegration\FrontendFilter->getFilters()
#3 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridFilterBlock.php(130): MetaModels\FrontendIntegration\FrontendFilter->getMetaModelFrontendFilter(Object(MetaModels\FrontendIntegration\Content\Filter))
#4 system\modules\core\classes\Hybrid.php(239): MetaModels\FrontendIntegration\HybridFilterBlock->compile()
#5 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\MetaModelHybrid.php(109): Contao\Hybrid->generate()
#6 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridFilterBlock.php(119): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#7 system\modules\core\library\Contao\Controller.php(484): MetaModels\FrontendIntegration\HybridFilterBlock->generate()
#8 system\modules\core\modules\ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system\modules\core\modules\Module.php(287): Contao\ModuleArticle->compile()
#10 system\modules\core\modules\ModuleArticle.php(67): Contao\Module->generate()
#11 system\modules\core\library\Contao\Controller.php(417): Contao\ModuleArticle->generate(false)
#12 system\modules\core\library\Contao\Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system\modules\core\pages\PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#14 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}
```

MM-List:
```
Fatal error: Uncaught exception RuntimeException with message Could get metamodel id: 1 thrown in composer\vendor\metamodels\core\src\MetaModels\ItemList.php on line 329

#0 composer\vendor\metamodels\core\src\MetaModels\ItemList.php(258): MetaModels\ItemList->prepareMetaModel()
#1 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridList.php(105): MetaModels\ItemList->setMetaModel('1', '2')
#2 system\modules\core\classes\Hybrid.php(239): MetaModels\FrontendIntegration\HybridList->compile()
#3 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\MetaModelHybrid.php(109): Contao\Hybrid->generate()
#4 composer\vendor\metamodels\core\src\MetaModels\FrontendIntegration\HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#5 system\modules\core\library\Contao\Controller.php(484): MetaModels\FrontendIntegration\HybridList->generate()
#6 system\modules\core\modules\ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#7 system\modules\core\modules\Module.php(287): Contao\ModuleArticle->compile()
#8 system\modules\core\modules\ModuleArticle.php(67): Contao\Module->generate()
#9 system\modules\core\library\Contao\Controller.php(417): Contao\ModuleArticle->generate(false)
#10 system\modules\core\library\Contao\Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#11 system\modules\core\pages\PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#12 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#13 index.php(20): Contao\FrontendIndex->run()
#14 {main}

```

## Steps to reproduce

1. create MM with render settings and filter
2. add CE-MM-List and CE-Filter
3. delete MM and reload site at FE

**Comment by zonky2** [comment]
the current output as exception is a good way...
