### ISSUE TITLE
Fatal error in Parent - Child - Child environment

### ISSUE THREAD

**Issue by design23** [MetaModels/core#1209]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.1.1        |                                  |
| Contao version:                     |    3.5.31      |                                  |
| MetaModels version:                 |   2.0.0       |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |    dev-hotfix/beta-42      |    also: beta-41          |

## Issue description

Simple parent-child-child environment. 
Adding and editing parent => no problem.
Adding childs => no problem.
Adding child to child => error (see below)

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Data provider mm_projects not defined thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DefaultEnvironment.php on line 294
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Populator/DataProviderPopulator.php(85): ContaoCommunityAlliance\DcGeneral\DefaultEnvironment->getDataProvider('mm_projects')
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Populator/DataProviderPopulator.php(70): MetaModels\DcGeneral\Populator\DataProviderPopulator->injectServiceContainerIntoDataDrivers(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultDataProviderDefinition), Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Populator/MetaModelPopulatorTrait.php(43): MetaModels\DcGeneral\Populator\DataProviderPopulator->populate(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#3 [internal function]: MetaModels\DcGeneral\Populator\DataProviderPopulator->handle(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Factory/DcGeneralFactory.php(349): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Factory/DcGeneralFactory.php(297): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(93): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#9 system/modules/core/classes/Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_apartements', Array)
#10 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#11 contao/main.php(20): Contao\BackendMain->run()
#12 {main}
```

**Comment by zonky2** [comment]
Kann ich mit MM Core a17 und DCG b41 bestätigen... unter MM 2.1 tritt der Fehler nicht auf

**Comment by zonky2** [comment]
@stefanheimes Du hast noch eine alte Version, wo das geht? welche ist das...

**Comment by discordier** [comment]
@zonky2, @stefanheimes Do you have an installation to test or shall we postpone this issue?

**Comment by zonky2** [comment]
current check at MM 2.0:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Data provider mm_mitarbeiterliste not defined thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DefaultEnvironment.php on line 295

#0 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Populator\DataProviderPopulator.php(86): ContaoCommunityAlliance\DcGeneral\DefaultEnvironment->getDataProvider('mm_mitarbeiterl...')
#1 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Populator\DataProviderPopulator.php(71): MetaModels\DcGeneral\Populator\DataProviderPopulator->injectServiceContainerIntoDataDrivers(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultDataProviderDefinition), Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Populator\MetaModelPopulatorTrait.php(44): MetaModels\DcGeneral\Populator\DataProviderPopulator->populate(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#3 [internal function]: MetaModels\DcGeneral\Populator\DataProviderPopulator->handle(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(352): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(300): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(93): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#9 system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_my_childchil...', Array)
#10 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#11 contao\main.php(20): Contao\BackendMain->run()
#12 {main}
```

**Comment by baumannsven** [comment]
@zonky2 I should think i have this fix.

**Comment by zonky2** [comment]
>@zonky2 I should think i have this fix.

Commit o.ä. verlinken!
