### ISSUE TITLE
Umstellung von SL auf ML schmeißt Fehler

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/core#189]
Wenn wir von einem SL (Single Language) auf ein ML (Multi Language) umstellen, müssen wir jedes Attribute öffnen und neu speichern, da alle Beschreibung noch im SL Mode gespeichert sind. Allerdings arbeitet MM dann schon im ML Mode und schmeißt den Fehler unten. 

```php
Warning: array_keys() expects parameter 1 to be array, string given in …/system/modules/metamodels/TableMetaModelHelper.php on line 132
#0 [internal function]: __error(2, 'array_keys() ex...', '/var/www/kunden...', 132, Array)
#1 …/system/modules/metamodels/TableMetaModelHelper.php(132): array_keys('Schema Bild')
#2 …/system/modules/metamodels/TableMetaModelAttribute.php(70): TableMetaModelHelper->makeMultiColumnName(Object(MetaModel), 'Sprache', 'Beschreibung', false, 'Schema Bild')
#3 …/system/modules/metamodels/TableMetaModelAttribute.php(118): TableMetaModelAttribute->setNameAndDescription(Object(MetaModel), Object(MetaModelAttributeRadiotable))
#4 …/system/modules/generalDriver/GeneralCallbackDefault.php(403): TableMetaModelAttribute->onLoadCallback(Object(DC_General))
#5 …/system/modules/generalDriver/DC_General.php(355): GeneralCallbackDefault->onloadCallback('tl_metamodel_at...')
#6 …/system/modules/backend/Backend.php(226): DC_General->__construct('tl_metamodel_at...')
#7 …/contao/main.php(120): Backend->getBackendModule('metamodels')
#8 …/contao/main.php(230): Main->run()
#9 {main}
```

**Comment by discordier** [comment]
Sollte gefixt sein.
