### ISSUE TITLE
(tng) contao 3.3.3 and MM2 fails to add filtersetting

### ISSUE THREAD

**Issue by be-meyer** [MetaModels/core#474]
I just created a new contao 3.3.3 with MetaModels tng nightly from today. I was able to create the backend stuff like backend render, setupmask and so on. While i tried to create the filter for the frontend which simply get all data it fails when trying to click add "add new filter" to my Filter. here is the error message:

```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Controller\DefaultController::isRootModel() must implement interface ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /usr/www/users/sulcoa/shop/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php on line 733 and defined in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 717

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(717): __error(4096, 'Argument 1 pass...', '/usr/www/users/...', 717, Array)
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(733): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->isRootModel(NULL)
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1628): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->enforceModelRelationship(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#3 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(968): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, Object(Closure), Object(Closure))
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(772): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste()
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(160): call_user_func_array(Array, Array)
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(72): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(120): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#13 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(233): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(256): MetaModels\BackendIntegration\Module->runDC()
#15 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(274): MetaModels\BackendIntegration\Module->performNormal()
#16 system/modules/core/classes/Backend.php(410): MetaModels\BackendIntegration\Module->generate()
#17 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#18 contao/main.php(293): Main->run()
#19 {main}


Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkCondition() must implement interface ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /usr/www/users/sulcoa/shop/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/RootCondition.php on line 147 and defined in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php on line 101

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php(101): __error(4096, 'Argument 1 pass...', '/usr/www/users/...', 101, Array)
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/RootCondition.php(147): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkCondition(NULL, Array)
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(733): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\RootCondition->matches(NULL)
#3 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(733): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->isRootModel(NULL)
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1628): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->enforceModelRelationship(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(968): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, Object(Closure), Object(Closure))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(772): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste()
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(160): call_user_func_array(Array, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(72): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(120): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#15 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(233): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(256): MetaModels\BackendIntegration\Module->runDC()
#17 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(274): MetaModels\BackendIntegration\Module->performNormal()
#18 system/modules/core/classes/Backend.php(410): MetaModels\BackendIntegration\Module->generate()
#19 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#20 contao/main.php(293): Main->run()
#21 {main}


Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkCondition() must implement interface ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /usr/www/users/sulcoa/shop/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php on line 41 and defined in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php on line 101

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php(101): __error(4096, 'Argument 1 pass...', '/usr/www/users/...', 101, Array)
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php(41): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkCondition(NULL, Array)
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php(113): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkAndFilter(NULL, Array)
#3 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/RootCondition.php(147): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\AbstractCondition::checkCondition(NULL, Array)
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(733): ContaoCommunityAlliance\DcGeneral\DataDefinition\ModelRelationship\RootCondition->matches(NULL)
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(733): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->isRootModel(NULL)
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1628): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->enforceModelRelationship(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(968): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, Object(Closure), Object(Closure))
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(772): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste()
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(160): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(72): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(120): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#17 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(233): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(256): MetaModels\BackendIntegration\Module->runDC()
#19 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(274): MetaModels\BackendIntegration\Module->performNormal()
#20 system/modules/core/classes/Backend.php(410): MetaModels\BackendIntegration\Module->generate()
#21 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#22 contao/main.php(293): Main->run()
#23 {main}


Fatal error: Call to a member function getProperty() on a non-object in /usr/www/users/sulcoa/shop/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php on line 87
```

I hope you can help me and did unterstand what i am trying to say. 

chears,
BennX

**Comment by psren** [comment]
Also bei mir ist alles auf dem aktuellsten Stand.
Aber jetzt bekomme ich seit neuestem diesen Fehler.

```php

Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Controller\DefaultController::setParent() must implement interface ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /kunden/302047_70174/kunden/reich/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 817 and defined in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 1175
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1175): __error(4096, 'Argument 1 pass...', '/kunden/302047_...', 1175, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(817): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->setParent(NULL, Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(758): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyAction(Array, Array, Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(642): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Array)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(505): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(546): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#14 contao/main.php(137): Contao\Backend->getBackendModule('metamodels')
#15 contao/main.php(288): Main->run()
#16 {main}

Fatal error: Call to a member function getProviderName() on null in /kunden/302047_70174/kunden/reich/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 1179
```

**Comment by psren** [comment]
Und zwar wenn ich ein Filter vom Typ "And" lösche.

**Comment by discordier** [comment]
Laut stack trace bist du hier aber nicht beim loeschen sondern beim pasten????
