### ISSUE TITLE
[TNG] "Speichern und neu" funktioniert nicht korrekt

### ISSUE THREAD

**Issue by mosesontheweb** [MetaModels/core#500]
Hallo,

hab heute einen Fehler auf einer Contao 3.2.12 mit Metamodels TNG entdeckt. Auf meiner Installation war dieser Effekt reproduzierbar:

- Neues Metamodel angelegt
- Klick auf "Speichern und neu"
- Nächstes Metamodel eingetragen
- Klick auf "Speichern und neu"
- Es ist ein Fehler aufgetreten

Fehlermeldung aus dem error.log:
```
[23-Jul-2014 19:00:08 GMT] PHP Fatal error: Uncaught exception 'ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException' with message 'Invalid condition, not in hierarchical mode!' thrown in /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php on line 210
#0 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(677): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#1 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1738): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteAfter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'sorting')
#2 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(978): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, Object(Closure), Object(Closure))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#4 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(160): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 /kunden/408228_2104/contao/3_2/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 /kunden/408228_2104/contao/3_2/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(72): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 /kunden/408228_2104/contao/3_2/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(120): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#11 /kunden/408228_2104/contao/3_2/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(233): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 /kunden/408228_2104/contao/3_2/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(256): MetaModels\BackendIntegration\Module->runDC()
#13 /kunden/408228_2104/contao/3_2/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(274): MetaModels\BackendIntegration\Module->performNormal()
#14 /kunden/408228_2104/contao/3_2/system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#15 /kunden/408228_2104/contao/3_2/contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#16 /kunden/408228_2104/contao/3_2/contao/main.php(293): Main->run()
#17 {main}
```

Gruß, Thomas

**Comment by tognit** [comment]
Auch bei mir eine Fehlermeldung:
```
[10-Jan-2015 12:44:59 Europe/Zurich] PHP Fatal error: Uncaught exception 'ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException' with message 'Unparsable encoded id value: ''' thrown in /home/public_html/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 141
#0 /home/public_html/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(71): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('')
#1 /home/public_html/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(51): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /home/public_html/composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /home/public_html/composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 /home/public_html/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 /home/public_html/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(114): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 /home/public_html/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(240): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 /home/public_html/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(265): MetaModels\BackendIntegration\Module->runDC()
#9 /home/public_html/composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(285): MetaModels\BackendIntegration\Module->performNormal()
#10 /home/public_html/system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#11 /home/public_html/contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#12 /home/public_html/contao/main.php(293): Main->run()
#13 {main}
```
MM = dev-tng vom 09.01.2014
Contao = 3.2.16

**Comment by xantippe** [comment]
dito
MM = dev-tng vom 08.01.2014
Contao = 3.3.7

**Comment by xantippe** [comment]
Funktioniert i.O. in
Contao 3.5.6
bundle_all 2.0.0 mit
metamodels/core 	2.0.0-alpha8

kann m.E. geschlossen werden...

**Comment by discordier** [comment]
Dann mach es doch einfach. :)

**Comment by xantippe** [comment]
dazu habe ich m.E. keine ausreichende Berechtigung - nur für meine Issues...
