### ISSUE TITLE
[TNG] Löschen eines MetaModels führt zu Fehlermeldung

### ISSUE THREAD

**Issue by cogizz** [MetaModels/core#531]
Folgende Situation:
- MetaModel Jahre
- MetaModel Presseberichte
Im MetaModel Presseberichte gibt es ein Attribute-Select, welches auf Jahre referenziert. Wenn ich jetzt das MetaModel Jahre vollständig lösche, erhalte ich folgende Fehlermeldung:

```

Fatal error: Uncaught exception Exception with message Query error: Table 'xxx.mm_press_year' doesn't exist (SELECT COUNT(mm_press_year.id) as mm_count, mm_press_year.* FROM mm_press_year GROUP BY mm_press_year.id ORDER BY mm_press_year.year) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

#0 system/modules/core/library/Contao/Database/Statement.php(254): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/attribute_select/src/system/modules/metamodelsattribute_select/MetaModels/Attribute/Select/Select.php(264): Contao\Database\Statement->execute()
#2 composer/vendor/metamodels/attribute_select/src/system/modules/metamodelsattribute_select/MetaModels/Attribute/Select/Select.php(127): MetaModels\Attribute\Select\Select->getFilterOptions(NULL, false)
#3 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(150): MetaModels\Attribute\Select\Select->getFieldDefinition(Array)
#4 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(196): MetaModels\BackendIntegration\InputScreen\InputScreen->translateProperty(Array, Object(MetaModels\MetaModel), 'meldung')
#5 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/InputScreen/InputScreen.php(76): MetaModels\BackendIntegration\InputScreen\InputScreen->translateRows(Array)
#6 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(262): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Array, Array, Array)
#7 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(344): MetaModels\BackendIntegration\ViewCombinations::fetchInputScreenDetails()
#8 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/ViewCombinations.php(420): MetaModels\BackendIntegration\ViewCombinations::bufferModels()
#9 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Dca/MetaModelDcaBuilder.php(311): MetaModels\BackendIntegration\ViewCombinations::getStandaloneInputScreens()
#10 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/Boot.php(171): MetaModels\Dca\MetaModelDcaBuilder->injectBackendMenu()
#11 system/initialize.php(245): MetaModels\BackendIntegration\Boot::perform()
#12 contao/main.php(18): require_once('/kunden/197278_...')
#13 {main}
```
Natürlich hätte ich auch zu erst das Attribute löschen können, aber dennoch wäre es gut, wenn es hier eine Meldung oder ähnliches geben würde. Weil so ist die Installation aktuell unbrauchbar.

Gelöst habe ich das Problem jetzt erstmal dadurch, das ich das Attribute aus der Datenbank gelöscht habe.

**Comment by xantippe** [comment]
getestet in core 2.0.0-alpha8

Das Löschen eines referenzierten MM bringt keine Fehlermeldungen - weder im BE noch im FE...

Das Isssue ist m.E. nicht mehr aktuell..

Als "FR" wäre es jedoch schön, wenn es beim Löschen eine Meldung gäbe wie "Das MM wird von folgenden MM referenziert: MM1, MM3, MM5! Wirklich löschen?"

**Comment by discordier** [comment]
Lassen wir es als FR offen oder moechtest du hierzu einen neuen FR auf 2.1 machen?

**Comment by xantippe** [comment]
FR: #938

=> schließen
