### ISSUE TITLE
[TNG] Warning: metamodel_prerendered: Undefined template variable: settings

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#552]
Mit den neuesten Commits und dev-tng (c2d00922) scheint das Template nicht zurechtzukommen ...
```
Warning: metamodel_prerendered: Undefined template variable: settings in composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Render/Template.php on line 112

#0 [internal function]: __error(512, 'metamodel_prere...', '/home/www/web1/...', 112, Array)
#1 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Render/Template.php(112): trigger_error('metamodel_prere...', 512)
#2 system/modules/metamodels/templates/metamodel_prerendered.html5(1): MetaModels\Render\Template->__get('settings')
#3 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/Render/Template.php(361): include('/home/www/web1/...')
#4 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/ItemList.php(817): MetaModels\Render\Template->parse('html5')
#5 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/FrontendIntegration/Content/ModelList.php(112): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#6 system/modules/core/elements/ContentElement.php(174): MetaModels\FrontendIntegration\Content\ModelList->compile()
#7 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/FrontendIntegration/Content/ModelList.php(64): Contao\ContentElement->generate()
#8 system/modules/core/library/Contao/Controller.php(468): MetaModels\FrontendIntegration\Content\ModelList->generate()
#9 system/modules/core/modules/ModuleArticle.php(196): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#10 system/modules/core/modules/Module.php(163): Contao\ModuleArticle->compile()
#11 system/modules/core/modules/ModuleArticle.php(59): Contao\Module->generate()
#12 system/modules/core/library/Contao/Controller.php(404): Contao\ModuleArticle->generate(false)
#13 system/modules/core/library/Contao/Controller.php(268): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#14 system/modules/core/pages/PageRegular.php(138): Contao\Controller::getFrontendModule('0', 'main')
#15 index.php(260): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#16 index.php(444): Index->run()
#17 {main}
´´´

**Comment by zonky2** [comment]
@discordier für was steht die Variable? wenn ich nach dieser Suche https://github.com/MetaModels/core/search?utf8=%E2%9C%93&q=strRendersettings taucht diese nur im "Head" der Templates auf und wird m.E. an keiner Stelle weiter verwendet...

**Comment by discordier** [comment]
Die wird in der Tat nur in:
* contao/templates/metamodel_prerendered.text 
* contao/templates/metamodel_unrendered.text 
Je auf Zeile 3 verwendet.

**Comment by zonky2** [comment]
auch bei *.html5 kommt es vor - nur die Suche spuckts nicht aus... https://github.com/MetaModels/core/blob/0f08e60206b910adb47e002a4e123e70059cffd5/contao/templates/metamodel_prerendered.html5#L13
ist für "hideLabel"
