### ISSUE TITLE
[TNG] Installationsprobleme auf Contao 3.3.5

### ISSUE THREAD

**Issue by hansen-pansen** [MetaModels/core#637]
Bei der händischen Installation des letzten nightly builds 2.x der MM auf mein Contao 3.3.5. Kommt es beim Versuch des DB-Updates via install.php zu folgender Fehlermeldeung:

```
Fatal error: Query error: Table 'contao_dv_db.tl_metamodel_dcasetting' doesn't exist (SHOW INDEXES FROM `tl_metamodel_dcasetting`)
#0 /Applications/MAMP/htdocs/conato-dev-git/system/modules/core/library/Contao/Database.php(203): Contao\Database\Statement->query('SHOW INDEXES FR...')
#1 /Applications/MAMP/htdocs/conato-dev-git/system/modules/core/library/Contao/Database/Mysqli.php(192): Contao\Database->query('SHOW INDEXES FR...')
#2 /Applications/MAMP/htdocs/conato-dev-git/system/modules/core/library/Contao/Database.php(295): Contao\Database\Mysqli->list_fields('tl_metamodel_dc...')
#3 /Applications/MAMP/htdocs/conato-dev-git/system/modules/core/library/Contao/Database.php(316): Contao\Database->listFields('tl_metamodel_dc...', true)
#4 /Applications/MAMP/htdocs/conato-dev-git/system/modules/metamodels/classes/src/MetaModels/Helper/UpgradeHandler.php(86): Contao\Database->fieldExists('published', 'tl_metamodel_dc...', true)
#5 /Applications/MAMP/htdocs/conato-dev-git/system/modules/metamodels/classes/src/MetaModels/Helper/UpgradeHandler.php(202): MetaModels\Helper\UpgradeHandler::upgradeDcaSettingsPublished()
#6 /Applications/MAMP/htdocs/conato-dev-git/system/modules/!metamodels-tng-branch/config/runonce_0.php(19): MetaModels\Helper\UpgradeHandler::perform()
#7 /Applications/MAMP/htdocs/conato-dev-git/system/modules/!metamodels-tng-branch/config/runonce.php(14): require_once('/Applications/M...')
#8 /Applications/MAMP/htdocs/conato-dev-git/system/modules/!metamodels-tng-branch/config/runonce.php(36): runonce_1147a0719ad8b8d78505be6e282b10bd->run()
#9 /Applications/MAMP/htdocs/conato-dev-git/system/modules/core/classes/Backend.php(266): include('/Applications/M...')
#10 /Applications/MAMP/htdocs/conato-dev-git/contao/install.php(624): Contao\Backend->handleRunOnce()
#11 /Applications/MAMP/htdocs/conato-dev-git/contao/install.php(192): InstallTool->adjustDatabaseTables()
#12 /Applications/MAMP/htdocs/conato-dev-git/contao/install.php(1148): InstallTool->run()
#13 {main} in system/modules/!metamodels-tng-branch/config/runonce.php on line 22

#0 [internal function]: __error(256, 'Query error: Ta...', '/Applications/M...', 22, Array)
#1 system/modules/!metamodels-tng-branch/config/runonce.php(22): trigger_error('Query error: Ta...', 256)
#2 system/modules/!metamodels-tng-branch/config/runonce.php(36): runonce_1147a0719ad8b8d78505be6e282b10bd->run()
#3 system/modules/core/classes/Backend.php(266): include('/Applications/M...')
#4 contao/install.php(624): Contao\Backend->handleRunOnce()
#5 contao/install.php(192): InstallTool->adjustDatabaseTables()
#6 contao/install.php(1148): InstallTool->run()
#7 {main}
```

**Comment by xantippe** [comment]
@hansen-pansen bei aktuellem Contao 3.5.x konnte ich keine Fehlermeldungen bei manueller Installation feststellen - ist das Ticket noch aktuell? bitte prüfen und ggf. schließen!
