### ISSUE TITLE
[TNG] Löschen eines Attributes welches in einer Condition genutzt wird führt zu Fehler

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#640]
Folgende Basis: Ein Attribute Select (Link-Type) und ein Attribute Text (URL). Beim Feld URL habe ich eine Condition hinterlegt wenn Link-Type = extern dann zeige URL an. Wenn ich jetzt das Attribut Link-Typ lösche, endet das mit folgendem Fehler:

```
Fatal error: Uncaught exception RuntimeException with message Could not retrieve attribute 20 from MetaModel mm_date. thrown in composer/vendor/metamodels/core/src/MetaModels/Events/DefaultPropertyConditionCreator.php on line 72 
```

Der Fehler entsteht dadurch, das zwar das Attribut gelöscht wird, jedoch nicht der Eintrag aus der Tabelle tl_dcasetting_condition. Aus dieser Tabelle müssten eigentlich alle Einträge gelöscht werden, welche auf das gelöschte Attribut referenzieren.

**Comment by xantippe** [comment]
getestet mit MM core 2.0.0-alpha8 => noch aktuell

```
Fatal error: Uncaught exception RuntimeException with message Could not retrieve attribute 8 from MetaModel mm_mitarbeiterliste. thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Events\DefaultPropertyConditionCreator.php on line 55

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Events\DefaultPropertyConditionCreator.php(92): MetaModels\Events\DefaultPropertyConditionCreator->getAttributeFromMetaModel(Object(MetaModels\MetaModel), '8')
#1 [internal function]: MetaModels\Events\DefaultPropertyConditionCreator->handle(Object(MetaModels\Events\CreatePropertyConditionEvent), 'metamodels.even...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(MetaModels\Events\CreatePropertyConditionEvent), 'metamodels.even...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.even...', Object(MetaModels\Events\CreatePropertyConditionEvent))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php(287): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.even...', Object(MetaModels\Events\CreatePropertyConditionEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php(319): MetaModels\BackendIntegration\InputScreen\InputScreen->transformCondition(Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php(113): MetaModels\BackendIntegration\InputScreen\InputScreen->transformConditions(Array)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(546): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Object(MetaModels\MetaModelsServiceContainer), Array, Array, Array, Array)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(609): MetaModels\Helper\ViewCombinations->buildInputScreen('mm_mitarbeiterl...')
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(622): MetaModels\Helper\ViewCombinations->getInputScreenDetails('mm_mitarbeiterl...')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\BackendModuleBuilder.php(304): MetaModels\Helper\ViewCombinations->getStandaloneInputScreens()
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\BackendModuleBuilder.php(76): MetaModels\BackendIntegration\BackendModuleBuilder->resolve()
#12 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Boot.php(115): MetaModels\BackendIntegration\BackendModuleBuilder->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(MetaModels\BackendIntegration\ViewCombinations))
#13 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\metamodels\config\event_listeners.php(65): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent))
#14 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#17 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\SubSystemBoot.php(128): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#18 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\metamodels\config\config.php(236): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#19 [internal function]: Contao\Config->{closure}(Object(Pimple))
#20 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dependency-container\src\DependencyInjection\Container\ContainerInitializer.php(116): call_user_func(Object(Closure), Object(Pimple))
#21 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dependency-container\src\DependencyInjection\Container\ContainerInitializer.php(449): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#22 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\initialize.php(243): DependencyInjection\Container\ContainerInitializer->init()
#23 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(16): require('C:\\Contao2Go\\ht...')
#24 {main}

```

**Comment by cyberlussi** [comment]
metamodels/core 2.0.0-alpha12 => noch aktuell

Workaround: da das Backend stetig nur noch die Fehlermeldung ausgibt, in der Datenbank direkt in der Tabelle tl_metamodel_dcasetting_condition die bemängelten attr_id händisch löschen.

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/pull/1017
