### ISSUE TITLE
Object of class MetaModels\Attribute\Text\Text could not be converted to string

### ISSUE THREAD

**Issue by tristanlins** [MetaModels/core#642]
```
Recoverable error: Object of class MetaModels\Attribute\Text\Text could not be converted to string in composer/vendor/metamodels/core/src/MetaModels/MetaModel.php on line 381
#0 [internal function]: __error(4096, 'Object of class...', '/var/www/vhosts...', 381, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(381): array_intersect(Array, Array)
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(444): MetaModels\MetaModel->fetchAdditionalAttributes(Array, Array, Array)
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(670): MetaModels\MetaModel->getItemsWithId(Array, Array)
#4 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(633): MetaModels\MetaModel->findByFilter(Object(MetaModels\Filter\Filter), 'sorting', 'tl_limit', NULL, 'desc', Array)
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(654): MetaModels\DcGeneral\Data\Driver->getItemsFromFilter(Object(MetaModels\Filter\Filter), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(62): MetaModels\DcGeneral\Data\Driver->fetchAll(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(302): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->loadCollection()
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(238): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(263): MetaModels\BackendIntegration\Module->runDC()
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(283): MetaModels\BackendIntegration\Module->performNormal()
#18 system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#19 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_fa...')
#20 contao/main.php(293): Main->run()
#21 {main}
```

Imo the `array_intersect` here cannot work:
https://github.com/MetaModels/core/blob/tng/src/MetaModels/MetaModel.php#L378-L381

Both arrays (or at least the left) contains objects. But the [documentation](http://php.net/manual/en/function.array-intersect.php) says:

> Note: Two elements are considered equal if and only if `(string) $elem1 === (string) $elem2`. In words: when the string representation is the same.

I changed the code this way:

```php

    protected function fetchAdditionalAttributes($ids, $result, $attrOnly = array())
    {
        $attributes = $this->getAttributeByNames($attrOnly);
        $attributeNames = array_intersect(
            array_keys($attributes),
            array_keys(array_merge($this->getComplexAttributes(), $this->getTranslatedAttributes()))
        );

        foreach ($attributeNames as $attributeName) {
            $attribute = $attributes[$attributeName];

            /** @var IAttribute $attribute */
            $attributeName = $attribute->getColName();

            ...
```

**Comment by xantippe** [comment]
@johannes-bittner & @Wagnerwagner 
könnt ihr "das" an einer aktuellen Version nochmal testen?

**Comment by xantippe** [comment]
Bitte testen!

**Comment by johannes-bittner** [comment]
Funktioniert bei mir jetzt korrekt. Version 2.0.0-alpha9.
