### ISSUE TITLE
Picker Popup Auswahl wird nicht gespeichert

### ISSUE THREAD

**Issue by Wagnerwagner** [MetaModels/core#651]
Ich habe ein Attribut "Mehrfachauswahl". In den Einstellungen der Backend-Eingabemaske habe ich diesem Attribut die Anzeigeoption "Als Checkbox-Wizard anzeigen" -> "Display as picker popup" zugewiesen.
Wenn ich nun in der Eingabemaske auf den Button "Auswahl ändern" klicken, erscheint die Lightbox bzw. das simple-modal-overlay mit der Auflistung aller Einträge. Dort aktiviere ich eine oder mehrere Checkboxen, klicke auf den Button "Anwenden" und die Lightbox schließt sich.
Egal ob ich nun den Datensatz speichere oder vor dem speichern des Datensatzes nochmals die Auswahl ändere sind die Checkboxen nicht mehr aktiviert.

Firefox Log schreibt:
```ReferenceError: reference to undefined property this.options.update 5e5d36609870.js:6
ReferenceError: reference to undefined property this.options.user.```
```getAttributeNode() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen getAttribute()```


Getestet mit Contao 3.3.6 und dem nightly tng vom 12.11.2014.

**Comment by xantippe** [comment]
Ich habe bei einem Mehrfachattribut eine Umstellung zum Testen auf den Picker-Popup gemacht - im Modal-Fenster erscheint

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, not in hierarchical mode! thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 210

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1125): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1146): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parentsOf(Object(MetaModels\DcGeneral\Data\Model), Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineParentsOfValues()
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(705): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeNodeStates()
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(728): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineModelState(Object(MetaModels\DcGeneral\Data\Model), 0)
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(831): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->treeWalkModel(Object(MetaModels\DcGeneral\Data\Model), 1, Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\dc-general\backend\generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#10 {main}
```

mm/core 2.0.0-alpha8

**Comment by xantippe** [comment]
Test MM alpha10 DCG beta34

* Checkboxmenü: funktioniert
* Checkbox-Wizard: funktioniert soweit - man darf aber die Reihenfolge nicht mit den Hamburgern verändern
* Pickup-Popup: mit schon vorhandenen Werten kommt
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, not in hierarchical mode! thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 209

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1125): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1146): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parentsOf(Object(MetaModels\DcGeneral\Data\Model), Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineParentsOfValues()
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(705): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeNodeStates()
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(728): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineModelState(Object(MetaModels\DcGeneral\Data\Model), 0)
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(831): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->treeWalkModel(Object(MetaModels\DcGeneral\Data\Model), 1, Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\dc-general\backend\generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#10 {main}
```
wenn vorher keine Werte vorhanden waren, kann Picker geöffnet werder - nach Auswahl+Anwenden+Speichern+neu öffnen des Picker kommt
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, not in hierarchical mode! thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 209

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1125): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->searchParentOf(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(1146): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parentsOf(Object(MetaModels\DcGeneral\Data\Model), Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineParentsOfValues()
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(705): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeNodeStates()
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(728): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->determineModelState(Object(MetaModels\DcGeneral\Data\Model), 0)
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(831): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->treeWalkModel(Object(MetaModels\DcGeneral\Data\Model), 1, Array)
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\dc-general\backend\generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#10 {main}
```
* Tag-Liste: funktioniert

ein Feld mit einer Ansichtsbedingung auf einen Tag-Wert wird angezeigt außer bei Pickup-Popup

**Comment by discordier** [comment]
See https://github.com/contao-community-alliance/dc-general/commit/d169f0dbcf4ccef8cc6c6ea643b5282a1bc3f3f2
