### ISSUE TITLE
Fatal error: Uncaught exception RuntimeException with message Condition of type conditionpropertyvalueis could not be transformed to an instance. thrown in composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php on line 256

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/core#681]
Nach dem neusten Update:

```
Fatal error: Uncaught exception RuntimeException with message Condition of type conditionpropertyvalueis could not be transformed to an instance. thrown in composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php on line 256

#0 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php(285): MetaModels\BackendIntegration\InputScreen\InputScreen->transformCondition(Array)
#1 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php(110): MetaModels\BackendIntegration\InputScreen\InputScreen->transformConditions(Array)
#2 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(536): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Object(MetaModels\MetaModelsServiceContainer), Array, Array, Array, Array)
#3 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(599): MetaModels\Helper\ViewCombinations->buildInputScreen('mm_xxx...')
#4 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(612): MetaModels\Helper\ViewCombinations->getInputScreenDetails('mm_xxx...')
#5 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/BackendModuleBuilder.php(292): MetaModels\Helper\ViewCombinations->getStandaloneInputScreens()
#6 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/BackendModuleBuilder.php(73): MetaModels\BackendIntegration\BackendModuleBuilder->resolve()
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Boot.php(113): MetaModels\BackendIntegration\BackendModuleBuilder->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(MetaModels\BackendIntegration\ViewCombinations))
#8 system/modules/metamodels/config/event_listeners.php(61): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#12 composer/vendor/metamodels/core/src/MetaModels/Helper/SubSystemBoot.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#13 system/modules/metamodels/config/config.php(224): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
#15 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(84): call_user_func(Object(Closure), Object(Pimple))
#16 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(328): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#17 system/initialize.php(244): DependencyInjection\Container\ContainerInitializer->init()
#18 contao/main.php(24): require('/var/www/vhosts...')
#19 {main}
```

**Comment by discordier** [comment]
Fixed in 5bbe920de1d62fdb9d47431f799718d67864dd38.

@Hauge did the problem reoccur? If so, please open a new ticket as it appears to be unrelated to this issue.
