### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by Hauge** [MetaModels/core#697]
Warning: Class 'Bit3\Contao\MetaPalettes\MetaPalettes' not found in system/modules/metapalettes/config/config.php on line 49

Neue Installation, contao 3.3.7, aktuelle nightly
```

Name                                                  Version                 Last modification
=================================================================================================
http://bit3.de
bit3/contao-meta-palettes                             1.9.0                   2015-01-06 07:04:07
-------------------------------------------------------------------------------------------------

http://c-c-a.org/
contao-community-alliance/backports-initialize-system dev-develop @ f5830e    2014-12-04 08:50:33
contao-community-alliance/dc-general                  dev-develop @ 4508e9    2014-12-09 16:38:55
contao-community-alliance/dependency-container        dev-develop @ 1da3ad    2014-12-04 06:08:29
contao-community-alliance/event-dispatcher            dev-develop @ d2da54    2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings      dev-contao-3.2 @ 36eee0 2014-11-08 18:39:45
contao-community-alliance/translator                  dev-develop @ 02feca    2014-06-05 08:57:37
-------------------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                            0.5.4                   2014-02-05 22:52:54
-------------------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                        dev-master @ 803a41     2014-12-08 23:13:26
-------------------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                         1.0.2                   2014-02-07 22:35:55
-------------------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard                    dev-dev @ ae91b5        2014-11-20 11:57:11
-------------------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                            dev-tng @ 06e094        2014-12-16 05:18:37
metamodels/attribute_checkbox                         dev-tng @ cca087        2014-12-17 05:49:52
metamodels/attribute_combinedvalues                   dev-tng @ 58cfd6        2014-11-12 17:48:31
metamodels/attribute_country                          dev-tng @ e3d00e        2014-12-17 02:05:46
metamodels/attribute_decimal                          dev-tng @ e5bba0        2014-12-16 00:35:07
metamodels/attribute_file                             dev-tng @ de070f        2014-11-12 17:45:51
metamodels/attribute_langcode                         dev-tng @ a3200d        2014-12-16 00:31:15
metamodels/attribute_longtext                         dev-tng @ 33e145        2014-11-07 15:00:37
metamodels/attribute_numeric                          dev-tng @ 4362ae        2014-11-20 12:50:06
metamodels/attribute_rating                           dev-tng @ 021ede        2014-11-20 12:37:30
metamodels/attribute_select                           dev-tng @ 477d53        2014-12-21 20:32:51
metamodels/attribute_tabletext                        dev-tng @ 23ee9c        2014-12-01 14:23:20
metamodels/attribute_tags                             dev-tng @ 865bf6        2015-01-05 16:20:56
metamodels/attribute_text                             dev-tng @ 4f551c        2014-12-18 18:29:58
metamodels/attribute_timestamp                        dev-tng @ 247563        2014-11-20 12:46:00
metamodels/attribute_translatedalias                  dev-tng @ e70a89        2014-12-04 02:28:26
metamodels/attribute_translatedcheckbox               dev-tng @ f0d25c        2014-08-27 19:01:34
metamodels/attribute_translatedcombinedvalues         dev-tng @ 487066        2015-01-06 06:14:57
metamodels/attribute_translatedfile                   dev-tng @ ec28cc        2015-01-06 06:18:32
metamodels/attribute_translatedlongtext               dev-tng @ fb21fb        2014-12-21 20:12:33
metamodels/attribute_translatedselect                 dev-tng @ 46e336        2014-12-11 18:54:34
metamodels/attribute_translatedtabletext              dev-tng @ 07ac20        2015-01-06 06:24:09
metamodels/attribute_translatedtags                   dev-tng @ 4adf60        2014-09-09 18:46:13
metamodels/attribute_translatedtext                   dev-tng @ f2ad30        2014-12-21 20:14:42
metamodels/attribute_url                              dev-tng @ ffd05a        2014-12-21 20:31:03
metamodels/bundle_all                                 dev-master @ f58927     2013-10-01 20:03:31
metamodels/bundle_attributes                          dev-master @ 058e26     2014-02-03 14:19:34
metamodels/bundle_filter                              dev-master @ 45d9cf     2013-05-03 07:16:44
metamodels/bundle_nontranslated                       dev-master @ 5f2b3f     2014-02-17 14:37:26
metamodels/bundle_translated                          dev-master @ 4bc0c1     2014-02-17 14:34:39
metamodels/core                                       dev-tng @ 8d377f        2015-01-06 04:47:07
metamodels/filter_checkbox                            dev-tng @ 230a0e        2014-11-11 17:30:48
metamodels/filter_fromto                              dev-tng @ db880c        2014-11-07 20:57:14
metamodels/filter_range                               dev-tng @ bf0103        2014-08-14 02:16:24
metamodels/filter_select                              dev-tng @ 8d07be        2014-11-07 21:01:34
metamodels/filter_tags                                dev-tng @ eaf3ea        2014-10-31 17:44:01
metamodels/filter_text                                dev-tng @ 75295a        2014-10-31 16:38:44
-------------------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                         1.1.x-dev @ bc2fc1      2014-04-20 07:24:09
-------------------------------------------------------------------------------------------------

http://symfony.com
symfony/event-dispatcher                              2.7.x-dev @ f812eb      2015-01-05 15:02:26
-------------------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder                 dev-develop @ 5f8997    2014-09-20 03:38:06
```

**Comment by design23** [comment]
Hier ebenfalls.

**Comment by discordier** [comment]
Da scheint die autoloading information irgendwie floeten gegangen zu sein.

Besteht das Problem noch?
Habt ihr sicher alle alten autoload informationen entfernt?

**Comment by design23** [comment]
Ich habe nochmal alles MM-relevante gelöscht und neu installiert – gleiches Ergebnis.

Was genau meinst Du mit "autoload informationen entfernt"?

**Comment by discordier** [comment]
See https://github.com/bit3/contao-meta-palettes/issues/32

**Comment by Hauge** [comment]
Ähm, ich versteh das nicht sorry,
habe jetzt die neueste nightly auf einem jungräulichen 3.3.7 installiert.
```
Name                                                  Version                 Last modification
=================================================================================================
http://bit3.de
bit3/contao-meta-palettes                             1.9.0                   2015-01-06 07:04:07
-------------------------------------------------------------------------------------------------

http://c-c-a.org/
contao-community-alliance/backports-initialize-system dev-develop @ f5830e    2014-12-04 08:50:33
contao-community-alliance/dc-general                  dev-develop @ 4508e9    2014-12-09 16:38:55
contao-community-alliance/dependency-container        dev-develop @ 1da3ad    2014-12-04 06:08:29
contao-community-alliance/event-dispatcher            dev-develop @ d2da54    2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings      dev-contao-3.2 @ 36eee0 2014-11-08 18:39:45
contao-community-alliance/translator                  dev-develop @ 02feca    2014-06-05 08:57:37
-------------------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                            0.5.4                   2014-02-05 22:52:54
-------------------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                        dev-master @ 803a41     2014-12-08 23:13:26
-------------------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                         1.0.2                   2014-02-07 22:35:55
-------------------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard                    dev-dev @ ae91b5        2014-11-20 11:57:11
-------------------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                            dev-tng @ 06e094        2014-12-16 05:18:37
metamodels/attribute_checkbox                         dev-tng @ cca087        2014-12-17 05:49:52
metamodels/attribute_combinedvalues                   dev-tng @ 58cfd6        2014-11-12 17:48:31
metamodels/attribute_country                          dev-tng @ e3d00e        2014-12-17 02:05:46
metamodels/attribute_decimal                          dev-tng @ e5bba0        2014-12-16 00:35:07
metamodels/attribute_file                             dev-tng @ de070f        2014-11-12 17:45:51
metamodels/attribute_langcode                         dev-tng @ a3200d        2014-12-16 00:31:15
metamodels/attribute_longtext                         dev-tng @ 33e145        2014-11-07 15:00:37
metamodels/attribute_numeric                          dev-tng @ 4362ae        2014-11-20 12:50:06
metamodels/attribute_rating                           dev-tng @ 021ede        2014-11-20 12:37:30
metamodels/attribute_select                           dev-tng @ 477d53        2014-12-21 20:32:51
metamodels/attribute_tabletext                        dev-tng @ 23ee9c        2014-12-01 14:23:20
metamodels/attribute_tags                             dev-tng @ 4ecd49        2015-01-08 01:22:28
metamodels/attribute_text                             dev-tng @ 4f551c        2014-12-18 18:29:58
metamodels/attribute_timestamp                        dev-tng @ 247563        2014-11-20 12:46:00
metamodels/attribute_translatedalias                  dev-tng @ e70a89        2014-12-04 02:28:26
metamodels/attribute_translatedcheckbox               dev-tng @ f0d25c        2014-08-27 19:01:34
metamodels/attribute_translatedcombinedvalues         dev-tng @ 487066        2015-01-06 06:14:57
metamodels/attribute_translatedfile                   dev-tng @ ec28cc        2015-01-06 06:18:32
metamodels/attribute_translatedlongtext               dev-tng @ fb21fb        2014-12-21 20:12:33
metamodels/attribute_translatedselect                 dev-tng @ 46e336        2014-12-11 18:54:34
metamodels/attribute_translatedtabletext              dev-tng @ 07ac20        2015-01-06 06:24:09
metamodels/attribute_translatedtags                   dev-tng @ 5ec0ee        2015-01-08 04:02:57
metamodels/attribute_translatedtext                   dev-tng @ f2ad30        2014-12-21 20:14:42
metamodels/attribute_url                              dev-tng @ ffd05a        2014-12-21 20:31:03
metamodels/bundle_all                                 dev-master @ f58927     2013-10-01 20:03:31
metamodels/bundle_attributes                          dev-master @ 058e26     2014-02-03 14:19:34
metamodels/bundle_filter                              dev-master @ 45d9cf     2013-05-03 07:16:44
metamodels/bundle_nontranslated                       dev-master @ 5f2b3f     2014-02-17 14:37:26
metamodels/bundle_translated                          dev-master @ 4bc0c1     2014-02-17 14:34:39
metamodels/core                                       dev-tng @ 30374f        2015-01-08 12:22:21
metamodels/filter_checkbox                            dev-tng @ 230a0e        2014-11-11 17:30:48
metamodels/filter_fromto                              dev-tng @ db880c        2014-11-07 20:57:14
metamodels/filter_range                               dev-tng @ bf0103        2014-08-14 02:16:24
metamodels/filter_select                              dev-tng @ 8d07be        2014-11-07 21:01:34
metamodels/filter_tags                                dev-tng @ eaf3ea        2014-10-31 17:44:01
metamodels/filter_text                                dev-tng @ 75295a        2014-10-31 16:38:44
-------------------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                         1.1.x-dev @ bc2fc1      2014-04-20 07:24:09
-------------------------------------------------------------------------------------------------

http://symfony.com
symfony/event-dispatcher                              2.7.x-dev @ b81b65      2015-01-08 13:03:06
-------------------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder                 dev-develop @ 5f8997    2014-09-20 03:38:06
```
Gleich beim einloggen erhalte ich den Fehler:
```
Warning: Class 'Bit3\Contao\MetaPalettes\MetaPalettes' not found in system/modules/metapalettes/config/config.php on line 49

#0 [internal function]: __error(2, 'Class 'Bit3\Con...', '/home/www/stemp...', 49, Array)
#1 system/modules/metapalettes/config/config.php(49): class_alias('Bit3\Contao\Met...', 'MetaPalettes')
#2 system/modules/core/library/Contao/Config.php(145): include('/home/www/stemp...')
#3 system/modules/core/library/Contao/Config.php(112): Contao\Config->initialize()
#4 system/initialize.php(156): Contao\Config::getInstance()
#5 contao/index.php(24): require('/home/www/stemp...')
#6 {main}


Warning: Class 'Bit3\Contao\MetaPalettes\MetaPalettesBuilder' not found in system/modules/metapalettes/config/config.php on line 50

#0 [internal function]: __error(2, 'Class 'Bit3\Con...', '/home/www/stemp...', 50, Array)
#1 system/modules/metapalettes/config/config.php(50): class_alias('Bit3\Contao\Met...', 'MetaPalettesBui...')
#2 system/modules/core/library/Contao/Config.php(145): include('/home/www/stemp...')
#3 system/modules/core/library/Contao/Config.php(112): Contao\Config->initialize()
#4 system/initialize.php(156): Contao\Config::getInstance()
#5 contao/index.php(24): require('/home/www/stemp...')
#6 {main}
```
Die Fehlermeldung auf https://github.com/bit3/contao-meta-palettes/issues/32
lautet:
Class 'ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\DcaReadingDataDefinitionBuilder' not found 
> hängt das zusammen?

**Comment by discordier** [comment]
Genau, das haengt zusammen.
Das Problem liegt bei MetaPalettes und ist daher hier bei MetaModels falsch.
Deshalb habe ich es hier geschlossen und es geht im MetaPalettes ticket weiter.

**Comment by Hauge** [comment]
Thanx

**Comment by Hauge** [comment]
https://community.contao.org/de/showthread.php?54932-Aktueller-Nightly-funktioniert-nicht&p=354645#post354645
