### ISSUE TITLE
Fatal error during backend search for attribute

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#700]
Contao:    3.2.7
MMCore:  dev-tng (30374f79) via composer

In the backend of MetaModels it is possible to search the items for an defined attribute, currently when i try to do this i got following fatal error:

```
Fatal error: Uncaught exception RuntimeException with message Error processing filter array - unknown operation array ( 0 => array ( 'operation' => 'LIKE', 'property' => 'title', 'value' => '*test*', ), ) thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php on line 421
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(335): MetaModels\DcGeneral\Data\FilterBuilder->calculateSubfilter(Array, Object(MetaModels\Filter\Filter))
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(395): MetaModels\DcGeneral\Data\FilterBuilder->getAndOrFilter(Object(MetaModels\Filter\Filter), Array)
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(445): MetaModels\DcGeneral\Data\FilterBuilder->calculateSubfilter(Array, Object(MetaModels\Filter\Filter))
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(331): MetaModels\DcGeneral\Data\FilterBuilder->build()
#4 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(407): MetaModels\DcGeneral\Data\Driver->prepareFilter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultLimitElement.php(74): MetaModels\DcGeneral\Data\Driver->fetchAll(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultLimitElement.php(142): ContaoCommunityAlliance\DcGeneral\Panel\DefaultLimitElement->calculateTotal()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultPanel.php(92): ContaoCommunityAlliance\DcGeneral\Panel\DefaultLimitElement->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig), NULL)
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultPanelContainer.php(85): ContaoCommunityAlliance\DcGeneral\Panel\DefaultPanel->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig), NULL)
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(50): ContaoCommunityAlliance\DcGeneral\Panel\DefaultPanelContainer->initialize(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(302): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->loadCollection()
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll()
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(240): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(265): MetaModels\BackendIntegration\Module->runDC()
#20 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(285): MetaModels\BackendIntegration\Module->performNormal()
#21 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#22 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_kn...')
#23 contao/main.php(293): Main->run()
#24 {main}
```

**Comment by MrTool** [comment]
Here again the var_dump from the operation array:

```
array(2) { ["operation"]=> string(3) "AND" ["children"]=> array(1) { [0]=> array(2) { ["operation"]=> string(3) "AND" ["children"]=> array(1) { [0]=> array(3) { ["operation"]=> string(4) "LIKE" ["property"]=> string(5) "title" ["value"]=> string(7) "*kassa*" } } } } } array(1) { [0]=> array(3) { ["operation"]=> string(4) "LIKE" ["property"]=> string(5) "title" ["value"]=> string(7) "*kassa*" } } 
```

**Comment by discordier** [comment]
Please test.

**Comment by MrTool** [comment]
purrs like a kitten
