### ISSUE TITLE
[TNG] Filter bearbeiten (Unparsable encoded id value: '')

### ISSUE THREAD

**Issue by exatre** [MetaModels/core#703]
Beim bearbeiten der Filtereinstellungen erscheint folgende Fehlermeldung.

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 141
```

Die Meldung erscheint erst, nachdem beim Filter ein Feld mit Mehrfachauswahl hinzugefügt wurde.

(Mit dc-generatel Beta und Dev probiert)

**Comment by psren** [comment]
Ich bekomme die selbe Meldung wenn ich einen neuen Datensatz anlege.

```

Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 141
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/AbstractHandler.php(127): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(678): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\AbstractHandler::checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1301): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->checkLanguage()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(790): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), NULL, Object(Closure), Object(Closure))
#4 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#13 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#14 contao/main.php(293): Main->run()
#15 {main}
```

**Comment by discordier** [comment]
Besteht das Problem noch im aktuellen tng (mm + dcg) @tim-bec?

**Comment by psren** [comment]
Habe erst gestern installiert, also sollte das im aktuellen tng noch so sein.

Hier meine composer.lock.
https://gist.github.com/psren/7e1c35e9e0df77acd740

**Comment by tim-bec** [comment]
Im aktuellen tng + dev-develop dcg besteht das problem nicht.

**Comment by psren** [comment]
Okay das Problem ist dass die TNG Branches den dcg in der Beta-Version auflösen.
Auf dev umgestellt und es klappt.

**Comment by tim-bec** [comment]
Ja... @discordier wann ist denn mit einem neuen dcg tag zu rechnen?

**Comment by inred-froehlich** [comment]
Habe den selben Fehler mit aktuellen Contao und Metamodels.
Wie genau kann man auf dev umstellen?
