### ISSUE TITLE
Publish Icon does not work

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#709]
After updating the dc-general to achieve a working filter rule (couldn't be created) the publish icon ajax call of an item fails with following error:

```php

Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView::toggle() must be an instance of ContaoCommunityAlliance\DcGeneral\Action, string given, called in /usr/www/users/fruxsq/portal/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php on line 154 and defined in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php on line 848
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(848): __error(4096, 'Argument 1 pass...', '/usr/www/users/...', 848, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(154): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->toggle('publishtoggle_p...')
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(114): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(240): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(265): MetaModels\BackendIntegration\Module->runDC()
#9 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(285): MetaModels\BackendIntegration\Module->performNormal()
#10 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#11 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pa...')
#12 contao/main.php(293): Main->run()
#13 {main}

Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Command with name toggle not found thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/View/CommandCollection.php on line 185
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(864): ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\View\CommandCollection->getCommandNamed('toggle')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(154): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->toggle('publishtoggle_p...')
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(114): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(240): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(265): MetaModels\BackendIntegration\Module->runDC()
#9 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(285): MetaModels\BackendIntegration\Module->performNormal()
#10 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#11 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pa...')
#12 contao/main.php(293): Main->run()
#13 {main}
```

**Comment by discordier** [comment]
Fix has been merged.
