### ISSUE TITLE
Fehler beim Bearbeiten der Rendereinstellung eines Attributs

### ISSUE THREAD

**Issue by dmolineus** [MetaModels/core#714]
Möchte ich die Rendereinstellung eines Attributs bearbeiten, erhalte ich folgenden Fehler:

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralvalidArgumentException with message 3 matching palettes found. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Palette/PaletteCollection.php on line 132
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(656): ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\PaletteCollection->findPalette(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1304): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1277): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#12 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#13 contao/main.php(293): Main->run()
#14 {main}
```

Installiert ist `metamodels/core a9276d2f` und tritt sowohl mit dem der dc-general in von `dev-develop` sowie `beta21` auf.

**Comment by dmolineus** [comment]
Guess it's caused by https://github.com/MetaModels/core/commit/b717e66ab8c895682fe947b84b4336f1e9dcd3df. Forcing an commit before these changes, everything works fine.

**Comment by discordier** [comment]
Argh. bracket missing I guess... :(

**Comment by dmolineus** [comment]
Das hilft leider nicht weiter. Hab auf die aktuelle Version installiert.

Die PaletteCollection beinhaltet bei mir weiterhin drei Paletten "default", "tabletext" und "file" (Tabletext und File sind als Attributstypen in den Rendersettings vorhanden).

**Comment by dmolineus** [comment]
Ich habe nochmal einen näheren Blick drauf geworfen, wenn ich mir die Condition anschaue, die für das TableText Attribut gebaut wird, ist meines Erachtens die `OR_CONJUNCTION` fehl am Platz, es sollte von der Logik her ein `AND` sein.

Hier die Condition als Export:

```
     'condition' => 
    ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Condition\Palette\PaletteConditionChain::__set_state(array(
       'conditions' => 
      array (
        '00000000229b6af70000000003605f03' => 
        ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Condition\Palette\PaletteConditionChain::__set_state(array(
           'conditions' => 
          array (
            '00000000229b6af60000000003605f03' => 
            ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Condition\Palette\PaletteConditionChain::__set_state(array(
               'conditions' => 
              array (
                '00000000229b6af10000000003605f03' => 
                ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Condition\Palette\PropertyValueCondition::__set_state(array(
                   'propertyName' => 'attr_id',
                   'propertyValue' => 'tabletext',
                   'strict' => true,
                   'weight' => 1,
                )),
                '00000000229b6af00000000003605f03' => 
                ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Condition\Palette\PropertyValueCondition::__set_state(array(
                   'propertyName' => 'file_showImage',
                   'propertyValue' => 'tabletext',
                   'strict' => true,
                   'weight' => 1,
                )),
              ),
               'conjunction' => 'OR',
            )),
          ),
           'conjunction' => 'AND',
        )),
        '00000000229b6af30000000003605f03' => 
        MetaModels\DcGeneral\DataDefinition\Palette\Condition\Palette\RenderSettingAttributeIs::__set_state(array(
           'attributeType' => 'tabletext',
           'weight' => 1,
        )),
      ),
       'conjunction' => 'OR',
    )),
```

Zuständig dafür ist
https://github.com/MetaModels/core/blob/tng/src/MetaModels/DcGeneral/Events/Table/RenderSetting/Subscriber.php#L566 und https://github.com/MetaModels/core/blob/tng/src/MetaModels/DcGeneral/Events/Table/RenderSetting/Subscriber.php#L570

**Comment by discordier** [comment]
Bitte nochmal testen.

**Comment by MrTool** [comment]
Bei mir hats funktioniert

**Comment by dmolineus** [comment]
Diesmal passt's.
