### ISSUE TITLE
editing/adding attribute in backend editing causes fatal error

### ISSUE THREAD

**Issue by MrTool** [MetaModels/core#725]
Contao: 3.3.7
MM: dev-tng (fe79d3ee)
DCG: dev-develop (ea6fdc62)

Stack Trace:
```

Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Property sortable is mentioned in palette but not defined in propertyDefinition. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 203
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(406): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->ensurePropertyExists('sortable', Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultPropertiesDefinition))
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(665): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#4 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(113): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#12 contao/main.php(142): Contao\Backend->getBackendModule('metamodels')
#13 contao/main.php(293): Main->run()
#14 {main}
```

This occures if i add or edit an attribute in the backend input mask

**Comment by ae69** [comment]
Bei mir das gleiche bei Text-Attributen und Select sogar beim blauen Info oder Detailbutton.

Aber z.B. bei Attribut Alias oder Langtext  oder Checkbox ist alles ok

**Comment by wangaz** [comment]
same here

**Comment by cyberlussi** [comment]
contao 3.2.18
contao-community-alliance/dc-general 	dev-develop (fdd43c2a)
metamodels/bundle_all 	1.0.1
metamodels/core 	dev-tng (5eaeb7d8)


Neues Alias Attribut -> Speichern+Schließen

```

Fatal error: Uncaught exception InvalidArgumentException with message Could not retrieve MetaModel thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php on line 474

#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php(495): MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->createAttributeInstance(Array)
#1 [internal function]: MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->handleUpdateAttribute(Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(284): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(614): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->handlePostPersist()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#17 contao/main.php(137): Contao\Backend->getBackendModule('metamodels')
#18 contao/main.php(288): Main->run()
#19 {main}
```
Attribut wird aber gespeichert!

Attribut aufrufen -> Speichern+Neu:

```

Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 140

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(71): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php(51): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#8 contao/main.php(137): Contao\Backend->getBackendModule('metamodels')
#9 contao/main.php(288): Main->run()
#10 {main}
```

**Comment by cyberlussi** [comment]
Ergänzung: Das neu angelegte Attribut *scheint* vorhanden zu sein, in der DB aber wohl nicht. Denn wenn man einen neuen Eintrag in der MM Tabelle machen will:

![2015-01-31_15_01_08_-_metamodels_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/5988278/0832a0d6-a95a-11e4-8413-38e72cd465ca.png)

![2015-01-31_15_18_31_-_gruppen_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/5988341/78480a08-a95c-11e4-9536-374f9835f67e.png)

```
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'name' in 'field list' (UPDATE mm_tl_mm_gruppe SET name='Gins' WHERE id=3) thrown in system/modules/core/library/Contao/Database/Statement.php on line 279

#0 system/modules/core/library/Contao/Database/Statement.php(250): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/core/src/MetaModels/Attribute/BaseSimple.php(80): Contao\Database\Statement->execute('Gins')
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(889): MetaModels\Attribute\BaseSimple->setDataFor(Array)
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\Text\Text), Array, 'Gins', NULL)
#4 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), NULL, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(611): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#19 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_tl...')
#20 contao/main.php(288): Main->run()
#21 {main}
```
![2015-01-31_15_19_23_-_localhost_8888_localhost_develop_dancer-mm2_mm_tl_mm_gruppe_phpmyadmin_4_2_10](https://cloud.githubusercontent.com/assets/4976687/5988342/9163f1aa-a95c-11e4-90cf-409e6dcfebd3.png)

**Comment by stefanheimes** [comment]
Hi, 

yesterday I update some attributes and remove the "flag" and "sortable" field form the DCA. Can you please update the system and try again.

**Comment by cyberlussi** [comment]
Bei mir das gleiche Verhalten [heute TNG aktualisiert] wie gestern in https://github.com/MetaModels/core/issues/725#issuecomment-72318001 von mir gemeldet.

contao/core 	3.2.18
contao-community-alliance/dc-general 	dev-develop (fdd43c2a)
metamodels/bundle_all 1.0.1
metamodels/core 	dev-tng (b257c40b)

![mm725](https://cloud.githubusercontent.com/assets/4976687/5992130/67ef914e-aa1a-11e4-8047-5038bf7d9648.gif)

**Comment by stefanheimes** [comment]
Ich glaube wir haben hier 2 Fehler. Der eine Fehler im DCA Settings das andere beim Erstellen der Attribute. @MrTool Wie sieht es bei dir aus ?

**Comment by MrTool** [comment]
Hab von zuhause leider keine Möglichkeit mir das anzusehen. Ich werds morgen vormittag gleich mal ausprobieren.

**Comment by ae69** [comment]
Wie schon in #732 berichtet:
Nach Installieren des Composers und update aller Dateien funktioniert sowohl #732 als auch #725 vollkommen ok
Contao 3.4.3 und MM 2.0
PHP 5.4.7

**Comment by cyberlussi** [comment]
@ae69 ... habe eigentlich gerade eine neue 3.2.18 Installation mit MM gemacht, als erstes Composer installiert und dann alle Pakete ... Vielleicht installiere ich nochmal neu - nicht dass da "Updateleichen" rumliegen.

**Comment by cyberlussi** [comment]
Auch nach einer per Composer MM kompletten Löschung und Neuinstallation ... ich mache was anders und da sitzt dann der Fehler: ich füge ein neues Attribut per schnellem "paste new" ein. Wenn ich über "Neues Attribut" + "Einfügen nach"  mache - dann funktioniert alles!

Bug bezieht sich also nur auf "das schnelle (+)" ohne die Ablage zu benutzen.

![mm725-2](https://cloud.githubusercontent.com/assets/4976687/5993133/f97e0e08-aa45-11e4-9c80-969654d571ed.gif)

**Comment by MrTool** [comment]
Bei uns funktionierts nach nem update von MM dev-tng und dcGeneral auf Beta 22

**Comment by psren** [comment]
Hat vorhin bei mir auch nicht funktioniert:

Contao: 3.4.3
MM Core: b257c40
DCG: fdd43c2a
