### ISSUE TITLE
Eintrag kopieren funktioniert nicht

### ISSUE THREAD

**Issue by psren** [MetaModels/core#731]
Wenn ich einen Eintrag (Mehrsprachig) kopieren will bekomme ich folgenden Fehler

```

Warning: Illegal string offset 'operation' in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php on line 265
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(265): __error(2, 'Illegal string ...', '/kunden/302047_...', 265, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(301): MetaModels\DcGeneral\Data\FilterBuilder->buildNativeSqlProcedure(Object(MetaModels\DcGeneral\Data\FilterBuilderSql), Array)
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(332): MetaModels\DcGeneral\Data\FilterBuilder->optimizedFilter(Object(MetaModels\Filter\Rules\Condition\ConditionAnd), Array, 'AND')
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(403): MetaModels\DcGeneral\Data\FilterBuilder->getAndOrFilter(Object(MetaModels\Filter\Filter), Array)
#4 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(453): MetaModels\DcGeneral\Data\FilterBuilder->calculateSubfilter(Array, Object(MetaModels\Filter\Filter))
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(336): MetaModels\DcGeneral\Data\FilterBuilder->build()
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(523): MetaModels\DcGeneral\Data\Driver->prepareFilter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(581): MetaModels\DcGeneral\Data\Driver->isUniqueValue('title', 'Airmaster IC In...')
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(265): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->createClonedModel(Object(MetaModels\DcGeneral\Data\Model))
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->copy()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#18 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#19 contao/main.php(293): Main->run()
#20 {main}

Warning: Illegal string offset 'operation' in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php on line 265
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(265): __error(2, 'Illegal string ...', '/kunden/302047_...', 265, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(301): MetaModels\DcGeneral\Data\FilterBuilder->buildNativeSqlProcedure(Object(MetaModels\DcGeneral\Data\FilterBuilderSql), Array)
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(332): MetaModels\DcGeneral\Data\FilterBuilder->optimizedFilter(Object(MetaModels\Filter\Rules\Condition\ConditionAnd), Array, 'AND')
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(403): MetaModels\DcGeneral\Data\FilterBuilder->getAndOrFilter(Object(MetaModels\Filter\Filter), Array)
#4 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(453): MetaModels\DcGeneral\Data\FilterBuilder->calculateSubfilter(Array, Object(MetaModels\Filter\Filter))
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(336): MetaModels\DcGeneral\Data\FilterBuilder->build()
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(523): MetaModels\DcGeneral\Data\Driver->prepareFilter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(581): MetaModels\DcGeneral\Data\Driver->isUniqueValue('title', 'Airmaster IC In...')
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(265): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->createClonedModel(Object(MetaModels\DcGeneral\Data\Model))
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->copy()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#18 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#19 contao/main.php(293): Main->run()
#20 {main}

Fatal error: Uncaught exception RuntimeException with message Error Processing sub filter: '=' thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilderSql.php on line 191
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(280): MetaModels\DcGeneral\Data\FilterBuilderSql->addChild('=')
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(301): MetaModels\DcGeneral\Data\FilterBuilder->buildNativeSqlProcedure(Object(MetaModels\DcGeneral\Data\FilterBuilderSql), Array)
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(332): MetaModels\DcGeneral\Data\FilterBuilder->optimizedFilter(Object(MetaModels\Filter\Rules\Condition\ConditionAnd), Array, 'AND')
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(403): MetaModels\DcGeneral\Data\FilterBuilder->getAndOrFilter(Object(MetaModels\Filter\Filter), Array)
#4 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/FilterBuilder.php(453): MetaModels\DcGeneral\Data\FilterBuilder->calculateSubfilter(Array, Object(MetaModels\Filter\Filter))
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(336): MetaModels\DcGeneral\Data\FilterBuilder->build()
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(523): MetaModels\DcGeneral\Data\Driver->prepareFilter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(581): MetaModels\DcGeneral\Data\Driver->isUniqueValue('title', 'Airmaster IC In...')
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(265): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->createClonedModel(Object(MetaModels\DcGeneral\Data\Model))
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->copy()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(119): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(129): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#18 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#19 contao/main.php(293): Main->run()
#20 {main}
```

**Comment by discordier** [comment]
dcg version?

**Comment by psren** [comment]
~2.0

Hier meine composer.lock.
https://gist.github.com/psren/7e1c35e9e0df77acd740

**Comment by psren** [comment]
Ich habe jetzt DCG von b21 auf dev upgedated.
Bekomme den Fehler immer noch.

**Comment by markus151173** [comment]
Den Fehler und noch weitere habe ich auch mit Mehrsprachigkeit und Varianten beim Kopieren.

Zum Einsatz kommt Contao 3.2.18 unter WIN 7 Pro, XAMPP 1.8.2, PHP: 5.4.16.
MM habe ich mir von der Seite metamodel.me MetaModels 2.x als ZIP gezogen.

Mich würde mal interessieren welche Version ich nun einsetzen soll?

@discordier
Kannst du hierzu sagen welche Version für den produktiven Einsatz verwendet werden soll, und
Ob es an dem Setup (wie oben) zu den Fehlern kommt. 

Ich gehe davon aus, dass auf der metamodel.me die nightly-tng.zip immer die aktuellste stabile Version ist.

**Comment by cboelter** [comment]
Die nightly-tng ist der aktuelle Stand von Github. Also der aktuelle Entwicklungsstand.

**Comment by markus151173** [comment]
@cboelter
Kannst du mir hier bitte sagen welche Quelle ich für einen produktiven Liveeinsatz verwenden kann.
Am besten einen Link oder Info.

Ich installiere MM ohne composer direkt in /modules/ was bei allen meiner MM Projekten immer gut funktioniert.
Dazu habe ich immer die ZIP’s von der offiziellen Seite verwendet. 
Jetzt steh ich auf’m schlauch!

**Comment by cboelter** [comment]
Die Frage ist garnicht so leicht zu beantworten, eine zu 100% stabile Version gibt es aktuell nicht für Contao 3. Ich selbst nutze den TNG, den du auch installiert hast. Dieser funktioniert insgesamt schon ganz gut und wird mit der Zeit immer stabiler. Jedoch kann es sein das es hier und da noch etwas hapert.

Diese Fehler müssen dann halt hier in Github dokumentiert werden und kritische Fehler werden in der Regel auch recht schnell behoben.

**Comment by poutvie** [comment]
Bekomme die Fehlermeldung auch beim Anlegen eines neuen Datensatzes eines mehrsprachigen MMs. Aber nicht bei allen. Eines macht Probleme andere MM funktionieren. Werde nach Unterschieden suchen, die den Ausschlag geben.

contao 3.2.16
contao-community-alliance/dc-general 	dev-develop (a7b84c37)
metamodels/core 	dev-tng (d374dba4)

**Comment by poutvie** [comment]
Ich habe übersetzte MM mit Listenansichten mit dem grünen Plus zur Erstellung neuer Datensätze. Hier kann ich neue Datensätze erstellen, aber nicht kopieren. Beim kopieren wird kein Einfügesymbol angezeigt, aber keine Fehlermeldung.
![liste](https://cloud.githubusercontent.com/assets/8960545/6709384/423d1eb2-cd79-11e4-8709-c3501b21103d.PNG)
Und dann habe ich ein übersetztes MM mit einer Listenansicht mit dem MM-Symbol im Kopf und dem Klemmmappesymbol zum Einfügen neuer Datensätze. Kein grünes Plus zum Erstellen neuer Datensätze. Hier kommt die Fehlermeldung.
Ich finde aber nicht heraus welche Einstellung welche Liste macht.
![listeproducts](https://cloud.githubusercontent.com/assets/8960545/6709388/45df5166-cd79-11e4-9665-0e37e12d7722.PNG)

**Comment by poutvie** [comment]
Das Symbol im Listenkopf hat mit dem Render Mode in der Eingabemaske zu tun. 
Vielleicht habe ich die Produkte Liste zum Testen auf "Hirachical" eingestellt und dann einen neuen Datensatz eingefügen wollen, den Vorgang aber nicht abgeschlossen und wieder auf "Flat" umgestellt. Keine mehr Ahnung ob es so war, aber die Liste sieht so aus als hinge sie in diesem Status. Klemmbrett für oberste Ebene wird angezeigt, aber die zum Einfügen an anderer Stelle fehlen. Wenn ich nun das Klembrett anklicke, kommt die Fehlermeldung.

**Comment by poutvie** [comment]
Ich habe eine neue Eingabemaske erstellt. nun habe ich das Problem in  #768 beschrieben.

**Comment by poutvie** [comment]
Hier hat sich leider nichts geändert. Ich habe den Rendermode von "flat" auf "hirachical" und zurück geändert. Kein Unterschied. Klemmbrett wird gezeigt und beim Anklicken Fehlermeldung. Wenn ich das sorting auf manuell ändere, sehe ich ausgegraute Einfüge-Klemmbretter. 
![produkte](https://cloud.githubusercontent.com/assets/8960545/6937666/477def84-d85d-11e4-9439-09d432869c9e.JPG)

Ich kann aber immer noch keine neuen Datensätze erstellen oder bestehende kopieren.

**Comment by poutvie** [comment]
Noch was: sorting funktioniert nur, wenn ich einen Grouping type angebe. Grouping type "Do not Group" führt zur Sortierung nach id unabhängig davon was in rendersortattr steht.

**Comment by poutvie** [comment]
Habe ein "&act=clear-clipboard" in die URL eingefügt. Bekam dann wieder ein "neuer Datensatz"-Symbol. Beim Anklicken kam wieder das Clipboard-Symbol und folgende Fehlermeldung beim Klick auf Clipboard-Symbol:
```
Fatal error: Uncaught exception RuntimeException with message No sorting property defined for mm_products thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php on line 355

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php(173): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->calculate()
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1083): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->getResults()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(958): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), NULL, NULL)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(773): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(649): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(508): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, NULL, Array)
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(546): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#15 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#16 contao/main.php(288): Main->run()
#17 {main}
```
Sorting ist aber angelegt, funktioniert allerdings nicht mit "no Grouping". Nur wenn ich eine Gruppierung angebe, ist die Liste richtig sortiert. Beim Anlegen neuer Datensätze kommt in beiden Fällen obige Fehlermeldung.
