### ISSUE TITLE
Kein neuer Eintrag in MM wenn Varianten aktiviert

### ISSUE THREAD

**Issue by design23** [MetaModels/core#736]
Szenario: 
- Contao 3.2.18
- MM -> metamodels/core + metamodels/bundle_all via composer frisch installiert
- Neues MM angelegt (nur 3 Felder - Text, Alias, Bild), Varianten aktiviert

Klick auf "Create new item" ergibt folgenden Fehler:

```
Fatal error: Uncaught exception RuntimeException with message No sorting property defined for mm_product thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php on line 357
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php(175): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->calculate()
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1066): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->getResults()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(941): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), NULL, NULL)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(766): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(642): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(505): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, NULL, Array)
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(546): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#15 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_ch...')
#16 contao/main.php(288): Main->run()
#17 {main}
```

**Comment by design23** [comment]
So sieht das ganze aus, wenn man einen Eintrag machen möchte. Es erscheint sofort nur das Icon, das eigentlich für die Platzierung zuständig ist...
Beim Klick auf "Create new item" kommt die oben genannte Fehlermeldung.

![bildschirmfoto 2015-02-01 um 15 17 38](https://cloud.githubusercontent.com/assets/6112308/5992335/8834623a-aa25-11e4-82a6-98e9f9aeca20.png)

Und das kommt, wenn man eine neue Variante anlegen möchte. Hier fehlen die Icons komplett.

![bildschirmfoto 2015-02-01 um 15 17 49](https://cloud.githubusercontent.com/assets/6112308/5992336/8adeb1c0-aa25-11e4-81b3-cd293f3caa3c.png)

**Comment by cboelter** [comment]
Bei mir passiert das gleiche. Es scheint so, als wird das Event für die Action hinter dem Event nicht ausgeführt.

**Comment by cboelter** [comment]
Ich habe jetzt angefangen das ganze wieder lauffähig zu machen, werde morgen einen entsprechenden PR machen.

**Comment by tim-bec** [comment]
should be fixed
