### ISSUE TITLE
Spalten werden in Tabelle nicht angelegt

### ISSUE THREAD

**Issue by psren** [MetaModels/core#738]
Bei mir werden die Spalten des Metamodels nicht ordentlich in der Datenbank angelegt.
Dadurch ensteht der folgende Fehler
```php
atal error: Uncaught exception Exception with message Query error: Unknown column 'name' in 'field list' (UPDATE mm_tags SET name='Strategie' WHERE id=1) thrown in system/modules/core/library/Contao/Database/Statement.php on line 293
#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/core/src/MetaModels/Attribute/BaseSimple.php(80): Contao\Database\Statement->execute('Strategie')
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(889): MetaModels\Attribute\BaseSimple->setDataFor(Array)
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\Text\Text), Array, 'Strategie', NULL)
#4 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), NULL, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(611): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#19 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_ta...')
#20 contao/main.php(20): Contao\BackendMain->run()
#21 {main}
```

Ich habe die Attribute in einem sehr einfachen Metamodel ganz normal übers Backend angelegt.
Ich vermute dass es mit der Contao-Version zusammenhängt.

Contao: 3.4.3
MM Core: b257c40b
DCG: fdd43c2a

**Comment by psren** [comment]
Duplicate of #738

**Comment by psren** [comment]
Uuups, falsche Referenz.
Das hier war es #725
