### ISSUE TITLE
Eingabemaske: Fatal error DcGeneral 'is not editable' EditMask.php on line 160

### ISSUE THREAD

**Issue by emkayy** [MetaModels/core#741]
Nach einem Update heute bekomme ich unten stehende Fehlermeldung sobald ich die Daten eines MM bearbeiten möchte (Eingabemaske). Auflisten der Daten klappt noch und auch alle Einstellungen des MM lassen sich bearbeiten.
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_diagonal is not editable thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 160

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(644): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->checkEditable(Object(MetaModels\DcGeneral\Data\Model))
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#11 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_di...')
#12 contao/main.php(293): Main->run()
#13 {main}

```

**Comment by discordier** [comment]
In den Einstellungen der Eingabemaske die Haken bei Edit, Create und Delete gesetzt?

**Comment by emkayy** [comment]
Da wird doch glatt der Hund in der Pfanne verrückt! Hier hat sich ein neues Feature eingeschlichen ;)
Wäre nur schön, wenn dann kein Fatal Error käme sondern eine kleine Meldung: Sorry, editing not erlaubt.

Das würde nervigen Bugreports wie den meinigen vorbeugen.

Danke auf jeden Fall!

**Comment by discordier** [comment]
Da hast du recht.

**Comment by discordier** [comment]
@tim-bec Wir sollten mal eine Liste machen welche Fehlermeldungen wir praesentieren wollen.
Weiterhin sollten wir etliche eigene exception typen definieren.
