### ISSUE TITLE
Fehlermeldung nach Update: call_user_func() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/core#748]
Folgende Meldung erhalte ich im Front- und Backend seit dem Update auf die letzte TNG Version. Im Einsatz ist Contao 3.4.2.

Danke

```
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'MetaModels\DcGeneral\Events\Table\Attribute\Translated\Alias\PropertyAttribute' not found in system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php on line 164
#0 [internal function]: __error(2, 'call_user_func(...', '/var/www/Dev/ht...', 164, Array)
#1 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func('MetaModels\DcGe...', Object(ContaoCommunityAlliance\Contao\EventDispatcher\Event\CreateEventDispatcherEvent), 'ContaoCommunity...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'ContaoCommunity...', Object(ContaoCommunityAlliance\Contao\EventDispatcher\Event\CreateEventDispatcherEvent))
#3 system/modules/event-dispatcher/classes/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php(49): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('ContaoCommunity...', Object(ContaoCommunityAlliance\Contao\EventDispatcher\Event\CreateEventDispatcherEvent))
#4 system/modules/event-dispatcher/config/services.php(68): ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->create(Object(Closure), Object(Closure))
#5 system/modules/pimple-pimple/classes/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#6 system/modules/pimple-pimple/classes/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
#7 system/modules/metamodels/config/services.php(82): Pimple->offsetGet('event-dispatche...')
#8 system/modules/metamodels/config/services.php(107): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#9 system/modules/pimple-pimple/classes/lib/Pimple.php(126): DependencyInjection\Container\ContainerInitializer->{closure}(Object(Pimple))
#10 system/modules/pimple-pimple/classes/lib/Pimple.php(83): Pimple::{closure}(Object(Pimple))
#11 system/modules/metamodels/classes/src/MetaModels/Helper/SubSystemBoot.php(93): Pimple->offsetGet('metamodels-serv...')
#12 system/cache/config/config.php(1984): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#13 [internal function]: Contao\Config->{closure}(Object(Pimple))
#14 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(112): call_user_func(Object(Closure), Object(Pimple))
#15 system/modules/dependency-container/classes/src/DependencyInjection/Container/ContainerInitializer.php(445): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#16 system/initialize.php(243): DependencyInjection\Container\ContainerInitializer->init()
#17 contao/main.php(16): require('/var/www/Dev/ht...')
#18 {main}
```

**Comment by MoppieMop** [comment]
Habe die gleiche Meldung mit Contao 3.2.19 und dem letzten TNG.

**Comment by chaela** [comment]
Ich hab ebenfalls den selben Fehler mit Contao 3.2.16 und dem neusten TNG (16.3.15 @ 14.28)

**Comment by tim-bec** [comment]
Bitte probiert mal den DCG dev-develop aus.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@tniebergall could you please have a final look at this and tell if your issue has been resolved?
