### ISSUE TITLE
Tabelle wird nicht richtig angelegt

### ISSUE THREAD

**Issue by psren** [MetaModels/core#753]
Beim Speichern eines neuen Attributs kommt es zu diesem Fehler:

```php

Fatal error: Uncaught exception InvalidArgumentException with message Could not retrieve MetaModel thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php on line 474
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/Attribute/Subscriber.php(495): MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->createAttributeInstance(Array)
#1 [internal function]: MetaModels\DcGeneral\Events\Table\Attribute\Subscriber->handleUpdateAttribute(Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(284): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(614): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->handlePostPersist()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#17 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodels')
#18 contao/main.php(20): Contao\BackendMain->run()
#19 {main}
```

Die Datenbank wird nicht richtig aktualisiert. Daher kommt es beim Anlegen eines neuen Items zu diesem Fehler:

```php

Fatal error: Uncaught exception Exception with message Query error: Unknown column 'title' in 'field list' (UPDATE mm_projects SET title='Projekt 1' WHERE id=2) thrown in system/modules/core/library/Contao/Database/Statement.php on line 293
#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/core/src/MetaModels/Attribute/BaseSimple.php(80): Contao\Database\Statement->execute('Projekt 1')
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(889): MetaModels\Attribute\BaseSimple->setDataFor(Array)
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\Text\Text), Array, 'Projekt 1', NULL)
#4 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), NULL, Array)
#5 composer/vendor/metamodels/core/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#6 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(611): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#13 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#18 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#19 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_pr...')
#20 contao/main.php(20): Contao\BackendMain->run()
#21 {main}
```

**Comment by tim-bec** [comment]
Kannst Du das bitte mal mit dem DCG dev-develop testen?

**Comment by xantippe** [comment]
@psren ist das beim aktuellen MM noch der Fall oder kann Ticket geschlossen werden?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@psren could you please have a final look at this and tell if your issue has been resolved?
