### ISSUE TITLE
Unknown column 'alias'

### ISSUE THREAD

**Issue by psren** [MetaModels/core#766]
I got a translatable alias attribute an a filter which uses it.
I'm getting the following error

```php

Fatal error: Uncaught exception Exception with message Query error: Unknown column 'alias' in 'where clause' (SELECT id FROM mm_categories WHERE alias IN ('kaese')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 279
#0 system/modules/core/library/Contao/Database/Statement.php(250): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/attribute_tags/src/MetaModels/Filter/Rules/FilterRuleTags.php(87): Contao\Database\Statement->execute(Array)
#2 composer/vendor/metamodels/attribute_tags/src/MetaModels/Filter/Rules/FilterRuleTags.php(102): MetaModels\Filter\Rules\FilterRuleTags->sanitizeValue()
#3 composer/vendor/metamodels/attribute_tags/src/MetaModels/Attribute/Tags/AbstractTags.php(249): MetaModels\Filter\Rules\FilterRuleTags->getMatchingIds()
#4 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/SearchAttribute.php(81): MetaModels\Attribute\Tags\AbstractTags->searchFor('kaese')
#5 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(113): MetaModels\Filter\Rules\SearchAttribute->getMatchingIds()
#6 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(252): MetaModels\Filter\Filter->getMatchingIds()
#7 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(725): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
#8 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(574): MetaModels\MetaModel->getCount(Object(MetaModels\Filter\Filter))
#9 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(798): MetaModels\ItemList->prepare()
#10 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(104): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#11 system/modules/core/classes/Hybrid.php(209): MetaModels\FrontendIntegration\HybridList->compile()
#12 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#13 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#14 system/modules/core/elements/ContentModule.php(54): MetaModels\FrontendIntegration\HybridList->generate()
#15 system/modules/core/library/Contao/Controller.php(457): Contao\ContentModule->generate()
#16 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#17 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#18 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#19 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#20 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), true, false, 'main')
#21 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#22 index.php(248): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#23 index.php(431): Index->run()
#24 {main}
```

**Comment by cboelter** [comment]
I fixed this error a few days ago, but I have to create a pull request for that.

**Comment by cboelter** [comment]
@psren i can send you the fixed file and you can check it?

**Comment by psren** [comment]
Yep i could do a pr.
You can send it to ph@wacg.de
