### ISSUE TITLE
Property bild (file) did not accept the value (The values differ. Encountered type NULL expected string (Found NULL, expected '')).

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#783]
Hi, 
mir ist folgendes aufgefallen: Neues MM angelegt: 1 Text als Pflichtfeld, 1 Bild (Attribut file), 1 Text. Dann neuen Eintrag anlegen. Ein leeres Bild wird nicht akzeptiert - obwohl kein Pflichtfeld.

![2015-03-21_12_51_15_-_gruppen_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/6764946/59205764-cfc9-11e4-94b5-51db159a3fab.png)
Wenn ich ein Bild angebe, kann der Eintrag erfolgreich gespeichert werden. Wenn ich diesen Eintrag dann bearbeite und das Bild wieder entferne:
![2015-03-21_12_57_15_-_gruppen_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/6764962/d28f5d16-cfc9-11e4-8da1-52f3754eef52.png)
```
Fatal error: Uncaught exception LogicException with message Property bild (file) did not accept the value (The values differ. Encountered type NULL expected string (Found NULL, expected '')). thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php on line 178

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(193): MetaModels\DcGeneral\Data\Model->setProperty('bild', '')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(225): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree('file')
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(250): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(463): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(122): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(78): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#6 system/modules/core/classes/Backend.php(249): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_gruppe', Array)
#7 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_gr...')
#8 contao/main.php(288): Main->run()
#9 {main}
```
contao/core 	3.2.19
contao-community-alliance/dc-general 	dev-develop (c21c7f9a)
metamodels/core 	dev-tng (79977020)

DCG oder eher MM?

**Comment by discordier** [comment]
Sollte mit 8212feb behoben sein.

**Comment by cyberlussi** [comment]
:8ball: Danke. behoben.

**Comment by cyberlussi** [comment]
Hm,
ja nein, geht doch nicht so ganz .... kein Bild auswählen: geht. Wenn ich aber ein Bild hinzufüge - speichern - geht - dann Eintrag bearbeiten - anderes Bild auswählen:

```
Fatal error: Uncaught exception LogicException with message Property image (file) did not accept the value (The values differ. Encountered type string expected array (Found '5�8�З�I��e�O', expected array ( 0 => '5�8�З�I��e�O', ))). thrown in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php on line 178

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(193): MetaModels\DcGeneral\Data\Model->setProperty('image', Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(225): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree('file')
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(250): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(463): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(122): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(78): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#6 system/modules/core/classes/Backend.php(249): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_team', Array)
#7 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_te...')
#8 contao/main.php(288): Main->run()
#9 {main}

```

**Comment by psren** [comment]
Related to: https://github.com/MetaModels/attribute_file/issues/45

**Comment by cboelter** [comment]
Same here.

**Comment by discordier** [comment]
Bitte in: MetaModels/attribute_file#45 weiter.
