### ISSUE TITLE
Error: Visibility conditions for attribute

### ISSUE THREAD

**Issue by padgrob** [MetaModels/core#786]
Ich habe für ein Tags Attribut folgende Ansichteinstellungen vorgenommen (siehe Screenshot).
Sobald ich die Einstellungen vornehme erhalte ich folgenden Fehlermeldung. 

Die Einstellungen können danach immer noch angepasst werden, die Fehlermeldung bleibt aber, auch erscheint ein Problem mit Umlauten im MM Breadcrumb.
In der Eingabemaske im Backend funktionieren die Einstellungen Korrekt. 

Contao 3.4.4

![ansichtseinstellungen atributte](https://cloud.githubusercontent.com/assets/11654144/6835052/6c0538be-d338-11e4-970e-292873b073ad.PNG)

``` php 
Warning: in_array() expects parameter 2 to be array, null given in system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/InputScreenCondition/Subscriber.php on line 298
#0 [internal function]: __error(2, 'in_array() expe...', '/usr/www/users/...', 298, Array)
#1 system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/InputScreenCondition/Subscriber.php(298): in_array('checkbox', NULL)
#2 [internal function]: MetaModels\DcGeneral\Events\Table\InputScreenCondition\Subscriber->getAttributeOptions(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php(285): ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber::getOptions(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\Properties\DefaultProperty))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber->renderReadablePropertyValue(Object(ContaoCommunityAlliance\DcGeneral\View\Event\RenderReadablePropertyValueEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\View\Event\RenderReadablePropertyValueEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\View\Event\RenderReadablePropertyValueEvent))
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ViewHelpers.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\View\Event\RenderReadablePropertyValueEvent))
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FormatModelLabelSubscriber.php(72): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ViewHelpers::getReadableFieldValue(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\Properties\DefaultProperty), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#15 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(253): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#16 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(317): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->parseModel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), 'tl_metamodel_dc...')
#17 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(474): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->generateTreeView(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'tree_xtnd')
#18 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(583): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->viewTree(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#19 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#20 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#21 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#22 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#23 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#24 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#25 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#26 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#27 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodels')
#28 contao/main.php(20): Contao\BackendMain->run()
#29 {main}

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/stagey/THA/letsfamily/system/helper/functions.php:68) in system/modules/core/library/Contao/Template.php on line 255
#0 [internal function]: __error(2, 'Cannot modify h...', '/usr/www/users/...', 255, Array)
#1 system/modules/core/library/Contao/Template.php(255): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(268): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(130): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/stagey/THA/letsfamily/system/helper/functions.php:68) in system/modules/core/library/Contao/Template.php on line 256
#0 [internal function]: __error(2, 'Cannot modify h...', '/usr/www/users/...', 256, Array)
#1 system/modules/core/library/Contao/Template.php(256): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(113): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(268): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(130): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main} ```

**Comment by discordier** [comment]
Das wurde doch in bc1acfec074e41bfb85074605c0570c8c1de1ad1 schon gefixt?

**Comment by padgrob** [comment]
OK, werde ich nochmals testen.

**Comment by discordier** [comment]
@padgrob Was ergab der Test?

**Comment by padgrob** [comment]
Sorry, das ich mich jetzt erst melde, war noch im Urlaub, werde es diese Woche testen.

**Comment by padgrob** [comment]
Mit der bc1acfe funktionierts ohne Fehlermeldung. 
Soll ich das Ticket gleich schliessen?

**Comment by discordier** [comment]
Wenn es erledigt ist, dann ja. :)
