### ISSUE TITLE
Fatal error bei Eingabe- / Ausgabe-Optionen definieren

### ISSUE THREAD

**Issue by Messa1** [MetaModels/core#792]
Hallo.

Forum:
https://community.contao.org/de/showthread.php?56511-Fatal-error-bei-Eingabe-Ausgabe-Optionen-definieren&p=364858#post364858

Ich habe Contao 3.3.20 am laufen und gerade die heutige nightly installiert.
Davor war nie MM auf der Seite am laufen.

Jetzt bekomme ich folgenden Fehler wenn ich bei meinem MM auf "Eingabe- / Ausgabe-Optionen definieren" klicke. (Siehe Anhang)

```
Fatal error: Class 'MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbDcaCombine' not found in /home/.sites/16/site839/web/system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/Table/DcaCombine/Subscriber.php on line 46
```
![bildschirmfoto 2015-04-03 um 12 27 55](https://cloud.githubusercontent.com/assets/3908658/7002611/c2115fee-dc4d-11e4-8706-f15d8b29ba37.png)

Meine Vorgehensweise:
Update Contao
Download MM nightly
Upload via FTP
Cache via FTP gelöscht
Datenbankupdate via Install.php

Contao Check sagt auch, dass alles im Bezug zu Contao OK ist.
![check](https://cloud.githubusercontent.com/assets/3908658/7010781/508d0916-dca4-11e4-8aa4-d63aa71d08d0.jpg)

**Comment by discordier** [comment]
Should be fixed in next nightly.

**Comment by Messa1** [comment]
Funktioniert :+1:

**Comment by andre5tz** [comment]
Heute aktualisiert über Composer:
Fatal error: Class 'MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbDcaCombine' not found in .../composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/DcaCombine/Subscriber.php on line 46

Contao 3.2.21
contao-community-alliance/dc-general 	dev-develop (388f7a7c) → 2.0.x-dev
metamodels/core dev-tng (e750d21b) → 2.0.x-dev
metamodels/bundle_all 1.0.1

LG
André

**Comment by discordier** [comment]
Den tng gibt es nicht mehr in MetaModels da er mit 2.0 alpha1 in master floss. Bitte stelle in deiner composer.json auf 2.0@dev oder dev-master um.

**Comment by andre5tz** [comment]
Danke für die Info. Wenn ich metamodels core umstelle, was mach ich dann mit dem dc_general? Muss der auch umgestellt werden?

Aktuell bekomme ich hier die folgende Fehlermeldung. Morgen schaue ich mir das nochmal genauer an.

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116
#0 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbBase.php(134): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbDcaCombine.php(37): MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbBase->extractIdFrom(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), 'pid')
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/BreadCrumb/BreadCrumbBase.php(205): MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbDcaCombine->getBreadcrumbElements(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), Array)
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Events/Table/DcaCombine/Subscriber.php(50): MetaModels\DcGeneral\Events\BreadCrumb\BreadCrumbBase->getBreadcrumb(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetBreadcrumbEvent))
#4 [internal function]: MetaModels\DcGeneral\Events\Table\DcaCombine\Subscriber->MetaModels\DcGeneral\Events\Table\DcaCombine\{closure}(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetBreadcrumbEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Object(Closure), Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetBreadcrumbEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetBreadcrumbEvent))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1422): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetBreadcrumbEvent))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(609): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->breadcrumb()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(585): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(149): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#18 contao/main.php(137): Contao\Backend->getBackendModule('metamodels')
#19 contao/main.php(288): Main->run()
#20 {main}
```

**Comment by andre5tz** [comment]
Thema ist für mich jetzt auch erledigt. Habe jetzt die richtige Metamodels-Version und scheinbar auch den richtigen dc_general erwischt 
metamodels/core dev-master (73c63624)
contao-community-alliance/dc-general dev-develop (388f7a7c)

anschließend nochmal alle Caches gelöscht und jetzt ist auch die Fehlermeldung weg.

Danke :-)
