### ISSUE TITLE
Fehler beim erstellen von neuen Datensätzen

### ISSUE THREAD

**Issue by Fr3d83** [MetaModels/core#802]
Hi,
ich bekomme folgende Fehlermeldung wenn ich einen neuen Datensatz erstelle:
Code:
```
[22-Apr-2015 09:09:04 GMT] PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid file array' thrown in /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/Helper/ToolboxFile.php on line 714
#0 /wwwroot.wwwnew/system/modules/metamodelsattribute_file/classes/src/MetaModels/Attribute/File/File.php(115): MetaModels\Helper\ToolboxFile::convertValuesToDatabase(NULL)
#1 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/MetaModel.php(873): MetaModels\Attribute\File\File->serializeData(NULL)
#2 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\File\File), Array, NULL, NULL)
#3 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), NULL, Array)
#4 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/DcGeneral/Data/Driver.php(562): MetaModels\Item->save()
#6 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/DcGeneral/Data/Driver.php(584): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1085): MetaModels\DcGeneral\Data\Driver->saveEach(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#8 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(614): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'sorting')
#9 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(677): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#10 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(780): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#11 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(755): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 /wwwroot.wwwnew/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 /wwwroot.wwwnew/system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 /wwwroot.wwwnew/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 /wwwroot.wwwnew/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 /wwwroot.wwwnew/system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#20 /wwwroot.wwwnew/contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_cu...')
#21 /wwwroot.wwwnew/contao/main.php(288): Main->run()
#22 {main}
```

Komisch ist nur, Bestehende Datensätze kann ich ändern und ohne Probleme abspeichern.
Auch wenn ich einen neuen Datensatz erstelle, bekomme ich die Fehlermeldung von oben, jedoch wurde der Datensatz gespeichert, wenn ich ihn jetzt bearbeite, kann ich ihn ohne Problme wieder Speichern, woran liegt das?
Habe auch das aktuellste nightly von heute installiert. 

Einstellung des MM:
![22-04-2015 12-27-06](https://cloud.githubusercontent.com/assets/6480582/7272891/b6279d76-e8ee-11e4-809d-8ce9368e7c16.jpg)

Attribute des MM:
![22-04-2015 12-27-39](https://cloud.githubusercontent.com/assets/6480582/7272892/b627fcbc-e8ee-11e4-9dc8-e4515cf4b00e.jpg)

**Comment by tim-bec** [comment]
Wenn Du mit Composer arbeitest, versuche mal bitte den DCG General dev-develop branch.

**Comment by Fr3d83** [comment]
Was heißt den genau, mit Composer arbeiten?

**Comment by tim-bec** [comment]
https://c-c-a.org/ueber-composer

**Comment by Fr3d83** [comment]
Ah ok, nein, ich habe es händisch über FTP Client gemacht.

**Comment by Fr3d83** [comment]
Soll ich jetzt den DCG General dev branch installieren?

**Comment by poutvie** [comment]
dürfte das selbe sein wie:  #768

**Comment by Fr3d83** [comment]
Dafür gibts es bis jetzt ja auch noch keinen fix, oder?

**Comment by poutvie** [comment]
@Fr3d83: nein

**Comment by Fr3d83** [comment]
Also heißt es jetzt auf ein neues nightly warten oder wie verfahre ich jetzt am besten?

**Comment by Fr3d83** [comment]
Gibt es schon was neues?

**Comment by xantippe** [comment]
der "File-Array-Fehler" ist schon seit einigen Versionen gefixt

m.E. kann das Ticket geschlossen werden
