### ISSUE TITLE
Fehler beim Anzeigen der Seitenstruktur (tl_page) mit dem Attribut "Mehrfachauswahl" und der Einstellung "Display as picker popup"

### ISSUE THREAD

**Issue by padgrob** [MetaModels/core#805]
Wenn ich beim Attribut "Mehrfachauswahl" auf die tl_page verweise und dann in der BE Erfassung die Option "Display as picker popup" auswähle erhalte ich im Backend fogende Fehlermeldung.

Fehlermeldung 1: erscheint wenn ich den Datensatz bearbeiten möchte.
![error1](https://cloud.githubusercontent.com/assets/11654144/7373185/4fc0d872-edcb-11e4-8fe5-87881542b54f.PNG)

Fehlermeldung 2: erscheint wenn ich das Attribut selber anpassen möchte, also Auswahl ändern.
![error2](https://cloud.githubusercontent.com/assets/11654144/7373217/6b18af5a-edcb-11e4-91d8-9e82acd3cebb.PNG)

Erstelle ich einen neuen Datensatz erscheint Fehlermeldung 1 & 2 nicht, Sobald ich aber den neu angelegten Datensatz speichere, erscheinen die Fehlermeldungen ebenfalls wieder.

Als Standard war die Option "Display as checkbox menu" aktiviert und da wurden auch schon seiten ausgewählt und zugewiesen.

Anbei noch die Einstellungen des Attributes
![attribute](https://cloud.githubusercontent.com/assets/11654144/7373287/c67a4926-edcb-11e4-9c15-8e18b32fb729.PNG)

MM wurde per tng am 23.02.2015 installiert.

Link zu Forum: https://community.contao.org/de/showthread.php?56890-Tags-Seitenstruktur-tl_page

**Comment by discordier** [comment]
Problem ist dass irgendein listener beim `ModelToLabelEvent` ein label/eine Argumentliste setzt welches nicht zur Argumentliste/zum Label passt.

@stefanheimes Wir myssen mal die listener evaluieren, welche da alle im Spiel sind.

**Comment by asaage** [comment]
Ich würde das Thema gern nochmal aufwärmen:
ich habe verschiedene Konfigurationen des Attributes durchgespielt (Einzel oder Mehrfachauswahl): immer das selbe Problem wenn ich es als Popup-Picker anzeigen lassen möchte.
```
[11-Nov-2015 17:34:13 Europe/Berlin] 
PHP Warning: vsprintf(): Too few arguments in /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php on line 993
#0 [internal function]: __error(2, 'vsprintf(): Too...', '/var/www/vhosts...', 993, Array)
#1 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(993): vsprintf('<a href="contao...', Array)
#2 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(1021): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->formatModel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#3 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(1087): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->parseModel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), 'tl_page_tree_13')
#4 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(656): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generateTreeView(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'tree')
#5 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(143): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generateAjax()
#6 /var/www/vhosts/contao/system/modules/dc-general/backend/generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#7 {main}
```

**Comment by discordier** [comment]
Immer nur bei tl_page?

**Comment by asaage** [comment]
hmm - müßt ich nochmal schauen ob ich ein anderes hirarchisches Beispiel finde.

**Comment by asaage** [comment]
funktioniert bei eigenen hierarchischen Metamodels
funktioniert bei tl_article (Hirarchie geht dabei verloren aber die entsteht ja eh durch tl_page referenz)
funktioniert bei tl_faq_category (hat von natur aus keine Hirarchie)
scheitert bei tl_content, tl_news (allerhand dcg Fehler)
scheitert bei tl_faq
```
[11-Nov-2015 19:43:20 Europe/Berlin] PHP Fatal error: Uncaught exception 'ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException' with message 'Unparsable encoded id value: ''' thrown in /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116
#0 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(801): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(870): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#4 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(608): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#5 /var/www/vhosts/contao/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#6 /var/www/vhosts/contao/system/modules/dc-general/backend/generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#7 {main}
```
ich kann nur Vermutungen anstellen...
Problem mit der Auflösung von pid (und oder ptable evl. fehlende Wurzel)

**Comment by padgrob** [comment]
Hallo Miteinander

Ich habe das Problem auch nur bei der tl_page

**Comment by fabian-ibr** [comment]
Auch bei mir erscheint dieses Problem, wenn ich auf tl_page verweise.

**Comment by zonky2** [comment]
der Fehler kommt dadurch zustande, dass in dem String von vsprintf eine URL mit Prozentzeichen halten ist/sein kann, so dass die Anzahl der Argumente nicht stimmt

siehe https://github.com/contao-community-alliance/dc-general/issues/144#issuecomment-218381851

**Comment by padgrob** [comment]
Hallo miteinander

Ich habe das mal kurz gemäss Hotfix (contao-community-alliance/dc-general#144 (comment)) angepasst. Die Seitenstruktur wird nun korrekt angezeigt und auch die Fehlermeldung ist weg. Was mir aber aufgefallen ist, das wenn ich einen Hauptnavigationspunkt öffne die Unsterseiten ganz unten am Seitenbaum angezeigt werden. Ist ein Hauptnavigationspunkt bereits geöffnet passts.

![screen](https://cloud.githubusercontent.com/assets/11654144/15180636/1fd73326-1783-11e6-93a4-329ad41a2371.PNG)

**Comment by zonky2** [comment]
die "Anzeigen-Verrutschung" ist an anderer Bug :-(
https://github.com/contao-community-alliance/dc-general/issues/89
https://github.com/contao-community-alliance/dc-general/issues/168

**Comment by padgrob** [comment]
Danke zonky2

**Comment by MoniqueHahnefeld** [comment]
Hi,
ich habe hier den Grund für die Fehlermeldung gefunden. Siehe Kommentar im Code. So habe ich das Problem für mich gelöst. Ich weis nicht ob es so das optimalste ist... :)
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php#L993
	//vsprintf won't work if label is html with more than one %, like the label for tl_page: checked this with that var_dump(explode('%',$event->getLabel())
	
	if ($model->getProperty('title') == NULL) {      
		$string = str_replace('>%s', '>'.$model->getProperty('name'), $event->getLabel());
	}else{
		$string = str_replace('>%s', '>'.$model->getProperty('title'), $event->getLabel());
	}

**Comment by MoniqueHahnefeld** [comment]
In diesen Zusammenhang habe ich auch in dem Tag-Attribut einen Bug gefunden.
https://github.com/MetaModels/attribute_tags/blob/master/src/MetaModels/Attribute/Tags/Tags.php#L59-L62
Den habe ich wie folgt fixen können:
 	if ($this->isTreePicker() && !empty($arrResult)) {

            $arrResult = implode(',', $arrResult);
            return $arrResult;
        }

**Comment by zonky2** [comment]
bitte beim Schreiben des Codes das "vorher-nachher" angeben mit "diff" nach den drei Ticks und - und +

**Comment by zonky2** [comment]
aktueller Test:
C 3.5.19
DCG  	dev-hotfix/beta-39 (91ca8ccb)
MM core  dev-hotfix/alpha-15 (be79e5a5)
MM tags  2.0.0-alpha6

Fehler erscheint schon bei der Anzeige der Eingabemaske

wenn statt tl_page z.B. tl_article verwendet wird, ist alles o.k.

```
Recoverable error: Argument 1 passed to tl_page::setRootType() must be an instance of DataContainer, instance of ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat given in system\modules\core\dca\tl_page.php on line 886

#0 system\modules\core\dca\tl_page.php(886): __error(4096, 'Argument 1 pass...', 'C:\\Contao2Go\\ht...', 886, Array)
#1 [internal function]: tl_page->setRootType(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Callback\Callbacks.php(71): call_user_func_array(Array, Array)
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Callback\AbstractCallbackListener.php(117): ContaoCommunityAlliance\DcGeneral\Contao\Callback\Callbacks::callArgs(Array, Array)
#4 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Callback\AbstractCallbackListener->__invoke(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Object(ContaoCommunityAlliance\DcGeneral\Contao\Callback\ContainerOnLoadCallbackListener), Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(308): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(232): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker.php(189): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->setUp(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder.php(448): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->__construct(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder.php(87): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder->buildWidget(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\Properties\DefaultProperty), Object(MetaModels\DcGeneral\Data\Model))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder::handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func('ContaoCommunity...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#15 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#16 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager.php(335): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('my_page', NULL)
#17 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(439): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->renderWidget('my_page', false, NULL)
#18 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(722): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#19 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(562): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#20 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(537): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#21 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#22 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(140): call_user_func_array(Array, Array)
#23 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#24 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#25 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#26 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#27 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#28 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#29 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#30 contao\main.php(20): Contao\BackendMain->run()
#31 {main}
```

**Comment by discordier** [comment]
Should be fixed by https://github.com/contao-community-alliance/dc-general/commit/37b8585d62786836decfefe1da37405142d08ed0, please test.

**Comment by zonky2** [comment]
fixed and works fine

![shot335](https://cloud.githubusercontent.com/assets/1045318/24440441/6afc05a6-1454-11e7-91f5-57acbb0a3c55.jpg)
