### ISSUE TITLE
too few parameters when empty default value in custom SQL filter.

### ISSUE THREAD

**Issue by MacKP** [MetaModels/core#819]
With `'` it works -> `name=auto_item&default=''`

Error Message:
```
Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system/modules/core/library/Contao/Database/Statement.php on line 328

#0 system/modules/core/library/Contao/Database/Statement.php(261): Contao\Database\Statement->replaceWildcards(Array)
#1 system/modules/metamodels/classes/src/MetaModels/Filter/Rules/SimpleQuery.php(91): Contao\Database\Statement->execute(Array)
#2 system/modules/metamodels/classes/src/MetaModels/Filter/Filter.php(113): MetaModels\Filter\Rules\SimpleQuery->getMatchingIds()
#3 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(252): MetaModels\Filter\Filter->getMatchingIds()
#4 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(725): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
#5 system/modules/metamodels/classes/src/MetaModels/ItemList.php(575): MetaModels\MetaModel->getCount(Object(MetaModels\Filter\Filter))
#6 system/modules/metamodels/classes/src/MetaModels/ItemList.php(799): MetaModels\ItemList->prepare()
#7 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#8 system/modules/core/classes/Hybrid.php(219): MetaModels\FrontendIntegration\HybridList->compile()
#9 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#10 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#11 system/modules/core/elements/ContentModule.php(56): MetaModels\FrontendIntegration\HybridList->generate()
#12 system/modules/core/library/Contao/Controller.php(469): Contao\ContentModule->generate()
#13 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#14 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
#15 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#16 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
#17 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#18 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#19 system/modules/core/controllers/FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#20 index.php(20): Contao\FrontendIndex->run()
#21 {main}
```

Viele Grüße

**Comment by discordier** [comment]
default value should default to `null` when key `default` is present but no value given.

**Comment by xantippe** [comment]
getestet in core 2.0.0-alpha8: mit
```alias = {{param::get?name=alias?default=}}```
oder
```alias = {{param::get?name=alias?default=''}}```
wird im SQL-Query
```alias = NULL```

kann m.E. geschlossen werden
