### ISSUE TITLE
Fatal error: Call to undefined method MetaModels\Events\ParseItemEvent::setDispatcher() in /htdocs/.../EventDispatcher.php

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/core#835]
Hi,

heute alles per Composer aktualisiert (CTO 3.2.21) erhalte ich sofort im Frontend bei Seiten mit MM Inhalt folgendes:

```
metamodels/bundle_attributes 	1.0.1 		
metamodels/bundle_filter 	1.0.0 		
metamodels/core 	dev-tng (cc6c8083) 		
```

```
Recoverable error: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event, instance of MetaModels\Events\ParseItemEvent given, called in /htdocs/composer/vendor/metamodels/core/src/MetaModels/Item.php on line 390 and defined in composer/vendor/symfony/event-dispatcher/EventDispatcher.php on line 40

#0 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(40): __error(4096, 'Argument 2 pass...', '/htdocs...', 40, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/Item.php(390): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.pars...', Object(MetaModels\Events\ParseItemEvent))
#2 composer/vendor/metamodels/core/src/MetaModels/Items.php(255): MetaModels\Item->parseValue('html5', Object(MetaModels\Render\Setting\Collection))
#3 composer/vendor/metamodels/core/src/MetaModels/Items.php(270): MetaModels\Items->parseValue('html5', Object(MetaModels\Render\Setting\Collection))
#4 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(804): MetaModels\Items->parseAll('html5', Object(MetaModels\Render\Setting\Collection))
#5 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#6 system/modules/core/classes/Hybrid.php(209): MetaModels\FrontendIntegration\HybridList->compile()
#7 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#8 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#9 system/modules/core/library/Contao/Controller.php(457): MetaModels\FrontendIntegration\HybridList->generate()
#10 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#16 index.php(254): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(443): Index->run()
#18 {main}


( ! ) Fatal error: Call to undefined method MetaModels\Events\ParseItemEvent::setDispatcher() in /htdocs/composer/vendor/symfony/event-dispatcher/EventDispatcher.php on line 46
Call Stack
#	Time	Memory	Function	Location
1	0.0010	322920	{main}( )	../index.php:0
2	0.1738	9009968	Index->run( )	../index.php:443
3	0.1846	9988920	Contao\PageRegular->generate( )	../index.php:254
4	0.2549	12783680	Contao\Controller->getFrontendModule( )	../PageRegular.php:129
5	0.4109	14068072	Contao\Controller->getArticle( )	../Controller.php:255
6	0.4121	14211048	Contao\ModuleArticle->generate( )	../Controller.php:393
7	0.4121	14211664	Contao\Module->generate( )	../ModuleArticle.php:50
8	0.4122	14215168	Contao\ModuleArticle->compile( )	../Module.php:139
9	0.4266	15393712	Contao\Controller->getContentElement( )	../ModuleArticle.php:187
10	0.4287	15731576	MetaModels\FrontendIntegration\HybridList->generate( )	../Controller.php:457
11	0.4287	15732064	MetaModels\FrontendIntegration\MetaModelHybrid->generate( )	../HybridList.php:55
12	0.4287	15733104	Contao\Hybrid->generate( )	../MetaModelHybrid.php:99
13	0.4287	15735016	MetaModels\FrontendIntegration\HybridList->compile( )	../Hybrid.php:209
14	0.4725	16999608	MetaModels\ItemList->render( )	../HybridList.php:105
15	0.5079	17662896	MetaModels\Items->parseAll( )	../ItemList.php:804
16	0.5079	17663552	MetaModels\Items->parseValue( )	../Items.php:270
17	0.5079	17663936	MetaModels\Item->parseValue( )	../Items.php:255
18	0.5441	18152816	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	../Item.php:390ª
```

**Comment by discordier** [comment]
Welche Version des event-dispatcher?

**Comment by cyberlussi** [comment]
contao-community-alliance/event-dispatcher 	1.3.0

Ist unter den Abhängigkeiten so gelistet.

**Comment by discordier** [comment]
Klingt so als haettest du eine komische Version des symfony event dispatcher.

**Comment by cyberlussi** [comment]
Danke. Das Update behebt den Fehler.
