### ISSUE TITLE
Template "Text" fehlt für Render-Einstellungen

### ISSUE THREAD

**Issue by Messa1** [MetaModels/core#838]
Wenn ich bei den Rendereisntellungen für das Frontend Ausgabeformat "Texte" wähle bekomme ich folgenden Fehler. Wenn ich auf HTML gehe wird das Feld ausgeben.
Attribut ist nur ein Textfeld und ein Alias Feld, es wird aber nur das Textfeld im Frontend ausgegeben.

Nightly von heute (18.07.2015 - 10:00 Uhr)
Contao 3.4.5

```
Warning: include(/home/SERVER/www/SERVER.com/new/system/modules/metamodels/templates/metamodel_prerendered.text) [function.include.php]: failed to open stream: No such file or directory in system/modules/metamodels/classes/src/MetaModels/Render/Template.php on line 301
#0 system/modules/metamodels/classes/src/MetaModels/Render/Template.php(301): __error(2, 'include(/home/g...', '/home/SERVER/w...', 301, Array)
#1 system/modules/metamodels/classes/src/MetaModels/Render/Template.php(301): MetaModels\Render\Template::parse()
#2 system/modules/metamodels/classes/src/MetaModels/ItemList.php(815): MetaModels\Render\Template->parse('text')
#3 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#4 system/modules/core/classes/Hybrid.php(219): MetaModels\FrontendIntegration\HybridList->compile()
#5 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#6 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#7 system/modules/core/library/Contao/Controller.php(469): MetaModels\FrontendIntegration\HybridList->generate()
#8 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#14 system/modules/core/controllers/FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}

Warning: include() [function.include.php]: Failed opening '/home/SERVER/www/SERVER.com/new/system/modules/metamodels/templates/metamodel_prerendered.text' for inclusion (include_path='.:/usr/local/share/pear') in system/modules/metamodels/classes/src/MetaModels/Render/Template.php on line 301
#0 system/modules/metamodels/classes/src/MetaModels/Render/Template.php(301): __error(2, 'include() [parse('text')
#3 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(105): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#4 system/modules/core/classes/Hybrid.php(219): MetaModels\FrontendIntegration\HybridList->compile()
#5 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(99): Contao\Hybrid->generate()
#6 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(55): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#7 system/modules/core/library/Contao/Controller.php(469): MetaModels\FrontendIntegration\HybridList->generate()
#8 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#14 system/modules/core/controllers/FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}
```

**Comment by discordier** [comment]
Da fehlt in der Tat ein Template. Das haben wir schlicht vergessen. Wird nachgereicht.

**Comment by xantippe** [comment]
@Messa1: kannst Du nicht einen PR dazu machen?

**Comment by Messa1** [comment]
@xantippe ich soll eine Pull Request machen?

**Comment by xantippe** [comment]
spricht was dagegen?

**Comment by Messa1** [comment]
Nein :) Mache ich gleich

**Comment by xantippe** [comment]
"gleich" ;-)

**Comment by Messa1** [comment]
@xantippe Arbeit geht immer vor :) Vor allem habe ich noch nie eine PR gemacht. Muss ich mir zuerst ansehen, nicht das es irgendwo in einem falschen Branch landet.

**Comment by xantippe** [comment]
ggf. mir die Dateien per E-Mail oder DropBox senden (Forum: "zonky")

**Comment by discordier** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by xantippe** [comment]
@Messa1 ... und?
