### ISSUE TITLE
Kind-Tabelle, Render mode parented: Fehlermeldung

### ISSUE THREAD

**Issue by pju-** [MetaModels/core#850]
Aktuelle Nightly, Contao 3.5.0
Ich habe ein Model, das ich als Kindtabelle von einem anderen Model darstellen möchte. Das Kind-Model hat nur ein Attribut (titel).

Wenn ich den Render-Mode auf Flat stelle, funktioniert alles. Wenn ich den Render-Mode auf Parented stelle, kriege ich eine Fehlermeldung, sobald ich auf das Icon zum Kind-Modell editieren klicke. Eventuell ist Ticket im DC-General besser aufgehoben, aber das wisst ihr besser als ich.

````
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Property titel is not registered. thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/DefaultPropertiesDefinition.php on line 110

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(238): ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultPropertiesDefinition->getProperty('aaa')
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(563): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->renderFormattedHeaderFields(Object(MetaModels\DcGeneral\Data\Model))
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php(623): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->viewParent(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), Object(MetaModels\DcGeneral\Data\Model))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ParentView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(146): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(75): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#11 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_pa...')
#12 contao/main.php(20): Contao\BackendMain->run()
#13 {main}
````

**Comment by asaage** [comment]
ist bereits bekannt:
issue #842
...hat aber schonmal funktioniert.

**Comment by tim-bec** [comment]
Danke, dann schließ ich das hier.
