### ISSUE TITLE
Fehlermeldung wenn shell_exec nicht verfügbar

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#862]
```
Warning: shell_exec() has been disabled for security reasons in system/modules/!composer/src/Controller/UpdatePackagesController.php on line 251

#0 [internal function]: __error(2, 'shell_exec() ha...', '/var/www/web120...', 251, Array)
#1 system/modules/!composer/src/Controller/UpdatePackagesController.php(251): shell_exec('/usr/bin/env ph...')
#2 system/modules/!composer/src/Controller/UpdatePackagesController.php(63): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->runDetached(Array, false)
#3 system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->handle(Object(Contao\Input))
#4 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}
```

z.B. Alfahosting

**Comment by discordier** [comment]
Ich glaube das sollte eher nach https://github.com/contao-community-alliance/composer-client oder nicht?

**Comment by xantippe** [comment]
jess => https://github.com/contao-community-alliance/composer-client/issues/259
