### ISSUE TITLE
Bug: Data manipulation permissions / Berechtigungen zur Datenanpassung

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#865]
die "Data manipulation permissions" bzw. "Berechtigungen zur Datenanpassung" in den Eingabemasken funktionieren (noch) nicht korrekt:

[_] Allow creating of items
wenn nicht erlaubt ist der Button in der Kopfzeile für "Neuer Datensatz" weg - soweit korrekt, aber "mehrere Bearbeiten" ist auch weg

[_] Allow editing of items
Stift-Icon ist noch da - wenn Klick auf diesen kommt Fehlermeldung
`Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_speisen is not editable thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 177`
Duplizieren müsste m.E. dann auch weg

[_] Allow deleting of items
Delete-Icon noch da - wenn Klick kommt noch Sicherheitsabfrage und anschließend Contao-Meldung "Ein Fehler ist aufgetreten!"

Contao 3.5.2
MM TNG 14.08.2015 (23:25h)

**Comment by xantippe** [comment]
aktueller Stand: core 2.0.0-alpha8
[...] Bearbeitung erlauben
* mehrere Bearbeiten ist weg
* Stift ist bei jedem Item noch da, aber bei Klick kommt Fehlermeldung

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_mitarbeiterliste is not editable thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php on line 177

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(648): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->checkEditable(Object(MetaModels\DcGeneral\Data\Model))
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(610): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(585): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(149): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#12 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#13 {main}
```

[...] Erstellen erlauben
* wenn nicht gesetzt, "Neu" ist weg
* grünes Kreuz ist noch da aber bei Klick kommt "Ein Fehler ist aufgetreten!"

[...] Löschen erlauben
* wenn nicht gesetzt, rotes Kreuz ist noch da 
* bei Klick kommt "Ein Fehler ist aufgetreten!"

**Comment by baumannsven** [comment]
@zonky2 i have update the check permission for model commands https://github.com/contao-community-alliance/dc-general/commit/2c354115e1eab7a436b0df6f482a125340c441d9

**Comment by zonky2** [comment]
and I check this...
look at https://github.com/contao-community-alliance/dc-general/issues/322#issuecomment-293090966

**Comment by zonky2** [comment]
merged
