### ISSUE TITLE
"Mehrere bearbeiten" erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by cptshit** [MetaModels/core#867]
Wenn ich bei mehreren Datensätzen versuche, die Funktion "Mehrere bearbeiten" zu verwenden, bekomme ich folgende Fehlermeldung:

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Action editAll is not implemented yet. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/SelectHandler.php on line 208

#0 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\SelectHandler->handleEditAllAction(Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/SelectHandler.php(59): call_user_func(Array, Array)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\SelectHandler->process()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(75): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#9 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_me...')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
```

Ich verwende Contao 3.4.4 und MM dev-tng (72080ad6)

**Comment by MacKP** [comment]
Das ist im Grunde eine Info die du bekommst:
"Action editAll is not implemented yet."
Gibt es also einfach noch nicht.

**Comment by hh-com** [comment]
Zur Info, man kann bei der Funktion "Mehrere Bearbeiten" die Datensätze nicht bearbeiten.
Kopieren hat bei mir schon funktioniert, mann muss dann aber die Feldnamen anpassen!
