### ISSUE TITLE
copying attributes from one model to another...

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#877]
...this will not create the necessary database-fields in the destinaton-model allthoug this action succeeds visually in the attribute-listing.
probably dcg-related...
(as a workaround you have to edit and save each single copied attribute)

**Comment by zonky2** [comment]
C 3.5.12
MM a11
DCG b36

copy of one or more get error
```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber::handlePostPersistModelEvent() must be an instance of ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent, instance of ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent given in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php on line 65

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php(65): __error(4096, 'Argument 1 pass...', 'C:\\Contao2Go\\ht...', 65, Array)
#1 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber->handlePostPersistModelEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(844): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(799): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doCloneAction(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(752): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyAction(Array, Array, Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(638): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Array)
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(423): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(140): call_user_func_array(Array, Array)
#11 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#16 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#17 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#18 contao\main.php(20): Contao\BackendMain->run()
#19 {main}
```
compare with https://github.com/contao-community-alliance/dc-general/issues/278

**Comment by zonky2** [comment]
after this fix https://github.com/contao-community-alliance/dc-general/commit/4c3b10b93df15f4252e2eb347adc3f85f16cb1d6 we can copy one or all attributes from a MM to another...
![shot239](https://cloud.githubusercontent.com/assets/1045318/15956646/34877f96-2eea-11e6-8fe0-33d298513f5d.jpg)

**BUT the database is empty :-(**
![shot240](https://cloud.githubusercontent.com/assets/1045318/15956650/3ed0d984-2eea-11e6-80f7-7508bd2089ca.jpg)

we must wait for "deep copy" at DCG

**Comment by discordier** [comment]
See also contao-community-alliance/dc-general#191 which is about deep-copy.

Copying of simple models has however been implemented meanwhile.
@zonky2 can we close this in favor of contao-community-alliance/dc-general#191

**Comment by zonky2** [comment]
@asaage pls observe the ticket at DCG ...
