### ISSUE TITLE
Fehlermeldung bei "Copy" von " Sorting and grouping" Eintrag

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#878]
Fehlermeldung bei "Copy" von " Sorting and grouping" Eintrag - anschließend ist der Eintrag aber vorhanden

TNG: 24.08.2015

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php(356): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber->initializePanels(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
```

**Comment by asaage** [comment]
https://github.com/contao-community-alliance/dc-general/issues/157

**Comment by xantippe** [comment]
getestet in /core 2.0.0-alpha8 => funktioniert ohne Fehlermeldungen
