### ISSUE TITLE
eig. SQL: "Too few arguments.." bei Formatierung FROM_UNIXTIME per %..

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#879]
```
SELECT id FROM mm_monate WHERE FROM_UNIXTIME(von_datum,'%Y-%m-%d') <= CURDATE() ORDER BY von_datum DESC LIMIT 1
```
wirft eine Fehlermeldung
```
Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system/modules/core/library/Contao/Database/Statement.php on line 331

#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#1 system/modules/metamodels/classes/src/MetaModels/Filter/Rules/SimpleQuery.php(90): Contao\Database\Statement->execute(Array)
#2 system/modules/metamodels/classes/src/MetaModels/Filter/Filter.php(116): MetaModels\Filter\Rules\SimpleQuery->getMatchingIds()
#3 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(251): MetaModels\Filter\Filter->getMatchingIds()
#4 system/modules/metamodels/classes/src/MetaModels/MetaModel.php(725): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
#5 system/modules/metamodels/classes/src/MetaModels/ItemList.php(575): MetaModels\MetaModel->getCount(Object(MetaModels\Filter\Filter))
#6 system/modules/metamodels/classes/src/MetaModels/ItemList.php(800): MetaModels\ItemList->prepare()
#7 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(115): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#8 system/modules/core/classes/Hybrid.php(231): MetaModels\FrontendIntegration\HybridList->compile()
#9 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#10 system/modules/metamodels/classes/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#11 system/modules/core/library/Contao/Controller.php(476): MetaModels\FrontendIntegration\HybridList->generate()
#12 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#13 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#14 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#15 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#16 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#17 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#18 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#19 index.php(20): Contao\FrontendIndex->run()
#20 {main}
```

**Comment by discordier** [comment]
contao uses `sprintf()` for filling in parameters.
Try: `SELECT id FROM mm_monate WHERE FROM_UNIXTIME(von_datum,'%%Y-%%m-%%d') <= CURDATE() ORDER BY von_datum DESC LIMIT 1` which should work.

**Comment by xantippe** [comment]
super! funktioniert
