### ISSUE TITLE
SearchablePages: Warnungen beim Aufbau von Suchindex

### ISSUE THREAD

**Issue by asaage** [MetaModels/core#902]
Nach dem ersten Schreck - aber nichts dramatisches.
Ich fange mal von hinten an:
ich habe in den Rendersettings die Angabe für Weiterleitungseite freigelassen weil ich das Rendersetting auf der Detailseite verwende - von dort aus wird nichtmehr weitergeleitet.
Beim Speichern wird das Feld aber mit {{link_url::}} ersetzt obwohl es nicht als Pflichtfeld gekennzeichnet ist.
![image](https://cloud.githubusercontent.com/assets/4138336/10966419/bc2dbcc2-83b3-11e5-871b-a2bdb57182ef.png)
Was zu folgendem Stacktrace beim Aufbau des Suchindex führt.
```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 62, Array)
#1 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(245): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL)
#3 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(456): MetaModels\BackendIntegration\SearchablePages->getJumpTosFor(Array, Object(MetaModels\MetaModel), Object(MetaModels\Filter\Filter), Object(MetaModels\Render\Setting\Collection), NULL)
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in system/modules/core/library/Contao/Controller.php on line 1082
#0 system/modules/core/library/Contao/Controller.php(1082): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 1082, Array)
#1 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(162): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(245): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL)
#7 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(456): MetaModels\BackendIntegration\SearchablePages->getJumpTosFor(Array, Object(MetaModels\MetaModel), Object(MetaModels\Filter\Filter), Object(MetaModels\Render\Setting\Collection), NULL)
#8 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#13 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 contao/main.php(20): Contao\BackendMain->run()
#15 {main}

Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 62, Array)
#1 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(245): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL)
#3 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(456): MetaModels\BackendIntegration\SearchablePages->getJumpTosFor(Array, Object(MetaModels\MetaModel), Object(MetaModels\Filter\Filter), Object(MetaModels\Render\Setting\Collection), NULL)
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in system/modules/core/library/Contao/Controller.php on line 1082
#0 system/modules/core/library/Contao/Controller.php(1082): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 1082, Array)
#1 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(162): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(245): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL)
#7 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(456): MetaModels\BackendIntegration\SearchablePages->getJumpTosFor(Array, Object(MetaModels\MetaModel), Object(MetaModels\Filter\Filter), Object(MetaModels\Render\Setting\Collection), NULL)
#8 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#13 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 contao/main.php(20): Contao\BackendMain->run()
#15 {main}

Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 62, Array)
#1 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#3 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in system/modules/core/library/Contao/Controller.php on line 1082
#0 system/modules/core/library/Contao/Controller.php(1082): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 1082, Array)
#1 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(162): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(318): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL)
#7 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#13 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 contao/main.php(20): Contao\BackendMain->run()
#15 {main}

Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent::__construct() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php on line 288 and defined in system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php on line 62
#0 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Events/Controller/GenerateFrontendUrlEvent.php(62): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 62, Array)
#1 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(288): ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent->__construct(NULL, NULL, NULL)
#2 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#3 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#4 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#5 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#6 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#7 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}

Recoverable error: Argument 1 passed to Contao\Controller::generateFrontendUrl() must be of the type array, null given, called in /var/www/vhosts/contao/system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php on line 126 and defined in system/modules/core/library/Contao/Controller.php on line 1082
#0 system/modules/core/library/Contao/Controller.php(1082): __error(4096, 'Argument 1 pass...', '/var/www/vhosts...', 1082, Array)
#1 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/ControllerSubscriber.php(126): Contao\Controller::generateFrontendUrl(NULL, NULL, NULL)
#2 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\ControllerSubscriber->handleGenerateFrontendUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(162): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent), 'contao.events.c...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#5 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(289): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.c...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\GenerateFrontendUrlEvent))
#6 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(325): MetaModels\BackendIntegration\SearchablePages->getBaseUrl(NULL, NULL, true)
#7 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(459): MetaModels\BackendIntegration\SearchablePages->removeEmptyDetailPages(Array)
#8 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/SearchablePages.php(405): MetaModels\BackendIntegration\SearchablePages->getMetaModelsPages(Array, NULL, NULL)
#9 system/modules/core/classes/RebuildIndex.php(78): MetaModels\BackendIntegration\SearchablePages->addPages(Array)
#10 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#11 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#12 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#13 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#14 contao/main.php(20): Contao\BackendMain->run()
#15 {main}

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/contao/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574
#0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/vhosts...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('FE_PREVIEW', '0', 1446633465, '/', '', false, false)
#2 system/modules/core/classes/RebuildIndex.php(94): Contao\System::setCookie('FE_PREVIEW', 0, 1446633465)
#3 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#6 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 contao/main.php(20): Contao\BackendMain->run()
#8 {main}

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/contao/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574
#0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/vhosts...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('FE_USER_AUTH', '2f9a5eb552b92f1...', 1446633465, '/', '', false, true)
#2 system/modules/core/classes/RebuildIndex.php(118): Contao\System::setCookie('FE_USER_AUTH', '2f9a5eb552b92f1...', 1446633465, NULL, NULL, false, true)
#3 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#6 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 contao/main.php(20): Contao\BackendMain->run()
#8 {main}

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/contao/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574
#0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/vhosts...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('FE_AUTO_LOGIN', '', 1446633465, '/', '', false, true)
#2 system/modules/core/classes/RebuildIndex.php(119): Contao\System::setCookie('FE_AUTO_LOGIN', NULL, 1446633465, NULL, NULL, false, true)
#3 system/modules/core/modules/ModuleMaintenance.php(52): Contao\RebuildIndex->run()
#4 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#5 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#6 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#7 contao/main.php(20): Contao\BackendMain->run()
#8 {main}

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/contao/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 294
#0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/vhosts...', 294, Array)
#1 system/modules/core/library/Contao/Template.php(294): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(120): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/contao/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 295
#0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/vhosts...', 295, Array)
#1 system/modules/core/library/Contao/Template.php(295): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(120): Contao\Template->output()
#3 system/modules/core/controllers/BackendMain.php(275): Contao\BackendTemplate->output()
#4 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```
Die Angabe einer Weiterleitungsseite behebt dies.
Alternativ habe ich das Rendersetting für meine Liste (mit den Weiterleitungs-links) bei den SearchablePages-einstellungen angegeben, was diese Fehler ebenfalls behebt und die Detailseiten indiziert...
Also die Logik erschließt sich mir noch nicht ganz.

**Comment by stefanheimes** [comment]
Ohne eine Seite, kann das System nicht bestimmen welches die Seite ist die in dem XML und Indizierung ersetzt werden soll. Daher wird hier einfach die JumpTo der Rendereinstellunge benutzt. 

Der Fehler ist daher verständlich, sollte hier aber einfach Ignoriert werden oder mit einer Fehlermeldung angemerkt werden.

**Comment by asaage** [comment]
Ich verwende jetzt die Rendereinstellung der Listenansicht (da ist der JumpTo ja auf jeden Fall gesetzt). Das indiziert mir dann auch die Detailseiten.

**Comment by stefanheimes** [comment]
Jip das auch die Idee dahinter gewesen, das hier einfach die Einstellung verwendet werden kann. Alternativ könne ein zweites Rendersetting verwendet werden mit anderen Filter, um zum Beispiele in der Suchseite oder den Sitemaps Elemente auszublenden.

**Comment by asaage** [comment]
Ahh - guter Tip...
Ich dachte nur, ich will die Detailseiten indizieren also wähl ich das Detailrendersetting aus.
Das führt einen ein bisschen auf den Holzweg.

**Comment by stefanheimes** [comment]
Wir haben ein Fehler drin, das System sollte nicht mit Errors den Fehler behandeln sondern es richtig abfangen :)

**Comment by asaage** [comment]
das wär natürlich vorbildlich :+1:

**Comment by asaage** [comment]
wenn das mal nicht das Selbe ist: #873

**Comment by n-m-k** [comment]
Mit den oben beschriebenen Maßnahmen kann ich auch den Fehlermeldungen aus #873 unterbinden.

**Comment by stefanheimes** [comment]
Should be fixed with the commit 5c43c268e4e02b77fbcac061c0b254e645b0848a ans the new version 2.0.0-alpha6.

**Comment by n-m-k** [comment]
Bei mir (#873) hat der Fix geholfen. Es erscheint keine Fehlermeldung mehr.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@asaage could you please have a final look at this and tell if your issue has been resolved?

**Comment by asaage** [comment]
resolved in terms of the recoverable errormessages :+1:
though leaving the jump-to empty in the rendersetting still adds an empty ```{{link_url::}}```
at some point ist should be made clear what @stefanheimes said in https://github.com/MetaModels/core/issues/902#issuecomment-154856380
