### ISSUE TITLE
Bug: Anlegen eines neuen MM und "Zurück"-Button OHNE Speichern => Error

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#946]
Klickt man auf "Neues MetaModel" und in der anschließend geöffneten Eingabemaske gleich wieder auf "Zurück", kommt folgende Fehlermeldung

MM core 2.0.0-alpha8

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (SELECT count(*) AS itemCount FROM) thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\library\Contao\Database\Statement.php on line 295

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\library\Contao\Database\Statement.php(264): Contao\Database\Statement->query()
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber.php(182): Contao\Database\Statement->execute()
#2 [internal function]: MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber->modelToLabel(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber.php(89): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(263): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->setListViewLabel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), Array)
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(330): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->viewList(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(149): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#20 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#21 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#22 {main}
```

**Workaround:** in der Tabelle tl_metamodel per phpMyAdmin den (letzten) Eintrag löschen, der bei "name" und "tableName" keine Werte enthält

**Comment by stefanheimes** [comment]
Ich weiß was der Fehler ist, ich kann es aber nicht nachstellen. Ich lege ein MM an und gehe ohne ein Eingabe auf den Zurück-Button, aber es passiert nichts.

**Comment by xantippe** [comment]
sihe auch https://community.contao.org/de/showthread.php?61220-Fatal-Error-Problem-mit-MySQL-Server-Version-bei-Aufruf-von-Metamodel

**Comment by stefanheimes** [comment]
Wie gesagt ich weiß wo der Fehler sitzt und auch warum, ich weiß nur nicht wie es überhaupt soweit kommen kann. Wenn ein leres MM angelegt wird, also die Grundeinstellungen, ich nicht speicher und zurück gehe, hab ich auch keine Leiche in der DB. Das ist mein Hauptproblem. Ich weiß nicht wie ich diese Leiche in der Datenbank hinbekommen soll. Das System versucht alle MM Tabellen auszulesen, da es hier aber noch keinen Name gibt stirbt der SQL daran.

**Comment by xantippe** [comment]
wenn ich an der Stelle bin

![shot97](https://cloud.githubusercontent.com/assets/1045318/12984006/267e6d30-d0ec-11e5-9f1f-dc9856729e67.jpg)

wird bei mir in der DB schon ein Datensatz angelegt

![shot98](https://cloud.githubusercontent.com/assets/1045318/12984049/52de9472-d0ec-11e5-825f-02fdc3271d33.jpg)

... wenn ich nichts speichere bzw. während des Zustandes in einem anderen Browser-Tab auf MM gehe, kommt der Fehler... die Fehlerursache ist ja soweit klar...

das Ganze ist m.E. ein generelles Problem und tritt z.B. auch bei Dateneingaben u.ä. auf (hier meist ohne Fehlermeldung) => sollte man beim Öffnen eines Panels schon einen (temporären) Datensatz anlegen oder nicht?

**Comment by discordier** [comment]
Das ist es eben. Der Dc General legt eben normalerweise keinen Datensatz an. Deshalb koennen wir es auch nicht nachstellen.
Bei mir passiert wie bei Stefan auch nix.

**Comment by MacKP** [comment]
Hmm ich kann das auch nachstellen: MM anlegen.. Formular nicht ausfüllen, sondern einfach zurück gehen. Fertig. Schon hab ich auch das Problem. Ich frage mich gerade wie ihr es nicht schafft das nachzustellen xD

**Comment by xantippe** [comment]
welchen DCG habt "Ihr", den "wir" nicht haben ;-)

**Comment by xantippe** [comment]
btw: ich habe das mit dem Verhalten vom Contao-Core verglichen: z.B. Seite anlegen: hat man die Eingabemaske für die Einstellungen einer neuen Seite, wird auch hier gleichzeitig ein DB-Eintrag angelegt - wir die Webseite geschlossen/Browser gekillt, ist der Eintrag in der DB wieder weg..!?? MySQL-Trigger?

**Comment by stefanheimes** [comment]
ICh wandere zwischen leter Version und den nächsten Version des DCG und MM her, ich werde das nochmal prüfen mit den alten und den neuen.

**Comment by discordier** [comment]
@xantippe kann das zu? contao-community-alliance/dc-general#183 ist ja fixed

**Comment by xantippe** [comment]
muss ich nochmal testen

**Comment by xantippe** [comment]
nein

DCG: dev-hotfix/2.0.0-beta34 (bb67abb3)

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (SELECT count(*) AS itemCount FROM) thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\library\Contao\Database\Statement.php on line 295

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\library\Contao\Database\Statement.php(264): Contao\Database\Statement->query()
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber.php(182): Contao\Database\Statement->execute()
#2 [internal function]: MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber->modelToLabel(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber.php(89): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(264): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->setListViewLabel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), Array)
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(324): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->viewList(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(141): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#20 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#21 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#22 {main}
```

**Comment by zonky2** [comment]
im DCG brauchts eine Funktion analog ```reviseTable()``` https://github.com/contao/core/blob/141fdc24579a46fc10d712a12f2b4459e11a5035/system/modules/core/drivers/DC_Table.php#L3169

**Comment by baumannsven** [comment]
@discordier um diese Sache kümmere ich mich

**Comment by AgentCT** [comment]
ich habe das gleiche Problem und ich komme garnicht in Metamodels.
Gibt es eine Lösung wie ich es wieder zum Laufen bekommen?

**Comment by zonky2** [comment]
per phpMyAdmin tl_metamodels bearbeiten bzw. entsprechende Zeile löschen

**Comment by discordier** [comment]
Should be fixed with DCG beta37

**Comment by cliffparnitzky** [comment]
Testing this with dev-hotfix/beta-37 (4a353578) is not possible due to errors.

**Comment by discordier** [comment]
could you enlighten me what errors those are?

**Comment by cliffparnitzky** [comment]
![image](https://cloud.githubusercontent.com/assets/1247552/17568440/0c8edb12-5f44-11e6-9cea-16cff4c0652f.png)

This is what i get when using the current commit of https://github.com/contao-community-alliance/dc-general/tree/hotfix/beta-37.

**Comment by discordier** [comment]
@cliffparnitzky, @stefanheimes could you have another look at this?
would be in need of a proper stack trace.

However, I am on Festival right now and therefore can not check myself.

**Comment by cliffparnitzky** [comment]
The probleme is located here: https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php#L145

The method is called from the PasteHandler with `create`. At this point `$this->getEvent()` returns `null`. This causes the error. But what shuould happen? @stefanheimes Any idea?

**Comment by zonky2** [comment]
Hi @cliffparnitzky - have you a workaround? I think, @stefanheimes is "afk" for this week...

**Comment by cliffparnitzky** [comment]
No, sorry, i have currently no solution. I've tested a little bit, but nothing worked. Maybe @discordier could give me a little hint, what to do there?

**Comment by discordier** [comment]
Follow up to contao-community-alliance/dc-general#290

**Comment by cliffparnitzky** [comment]
Fixed with https://github.com/contao-community-alliance/dc-general/commit/c217064f3435d340ef1766e968256b20a04cd003
