### ISSUE TITLE
Bug: Anzeigeeigenschaft angelegt ohne Typ ist per "Auge" aktivierbar => Error

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#947]
Wird eine Anzeigeeigenschaft einer Eingabemaske neu angelegt aber ohne Typauswahl verlassen,

![shot40](https://cloud.githubusercontent.com/assets/1045318/12145791/93d5fa88-b490-11e5-9af5-19d94783f3b7.jpg)

wird diese dennoch angelegt

und kann anschließend über das Auge aktiviert werden

![shot41](https://cloud.githubusercontent.com/assets/1045318/12145737/449a3a9c-b490-11e5-91a7-0ce7c3722229.jpg)

dann kommt folgende Fehlermeldung - Condition muss anschließend in DB gelöscht werden

```
Fatal error: Uncaught exception RuntimeException with message Condition of type could not be transformed to an instance. thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php on line 290

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php(319): MetaModels\BackendIntegration\InputScreen\InputScreen->transformCondition(Array)
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\InputScreen\InputScreen.php(113): MetaModels\BackendIntegration\InputScreen\InputScreen->transformConditions(Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(546): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Object(MetaModels\MetaModelsServiceContainer), Array, Array, Array, Array)
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(609): MetaModels\Helper\ViewCombinations->buildInputScreen('mm_mitarbeiterl...')
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\ViewCombinations.php(622): MetaModels\Helper\ViewCombinations->getInputScreenDetails('mm_mitarbeiterl...')
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\BackendModuleBuilder.php(304): MetaModels\Helper\ViewCombinations->getStandaloneInputScreens()
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\BackendModuleBuilder.php(76): MetaModels\BackendIntegration\BackendModuleBuilder->resolve()
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Boot.php(115): MetaModels\BackendIntegration\BackendModuleBuilder->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(MetaModels\BackendIntegration\ViewCombinations))
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\metamodels\config\event_listeners.php(65): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent))
#9 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#12 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\metamodels\core\src\MetaModels\Helper\SubSystemBoot.php(128): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#13 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\metamodels\config\config.php(236): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
#15 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dependency-container\src\DependencyInjection\Container\ContainerInitializer.php(116): call_user_func(Object(Closure), Object(Pimple))
#16 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dependency-container\src\DependencyInjection\Container\ContainerInitializer.php(449): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#17 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\initialize.php(243): DependencyInjection\Container\ContainerInitializer->init()
#18 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(16): require('C:\\Contao2Go\\ht...')
#19 {main}

```

**Comment by zonky2** [comment]
ist mit DCG beta38 gefixt https://github.com/contao-community-alliance/dc-general/tree/hotfix/beta-38
Datensatz wird nicht angelegt und man springt zurück in die Ansicht mit Clipboard
