### ISSUE TITLE
Error bei Kombination "Einf. Abfrage" mit stat. Parameter und {{param::filter

### ISSUE THREAD

**Issue by xantippe** [MetaModels/core#962]
es kommt im FE eine Fehlermeldung bei folgender Kombination
im Filter
* Oder mit
* Einfache Abfrage und statischem Parameter (test)
* Eig. SQL mit {{param::filter?name=test}}

in CE-MM-Liste
* **keine Auswahl** in Selectbox für den statischen Parameter

```
Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system/modules/core/library/Contao/Database/Statement.php on line 331

#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#1 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/SimpleQuery.php(90): Contao\Database\Statement->execute(Array)
#2 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(116): MetaModels\Filter\Rules\SimpleQuery->getMatchingIds()
#3 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/Condition/ConditionOr.php(98): MetaModels\Filter\Filter->getMatchingIds()
#4 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(116): MetaModels\Filter\Rules\Condition\ConditionOr->getMatchingIds()
#5 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(251): MetaModels\Filter\Filter->getMatchingIds()
#6 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(725): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
#7 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(575): MetaModels\MetaModel->getCount(Object(MetaModels\Filter\Filter))
#8 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(800): MetaModels\ItemList->prepare()
#9 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(115): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#10 system/modules/core/classes/Hybrid.php(231): MetaModels\FrontendIntegration\HybridList->compile()
#11 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#12 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#13 system/modules/core/library/Contao/Controller.php(476): MetaModels\FrontendIntegration\HybridList->generate()
#14 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#15 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#16 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#18 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 index.php(20): Contao\FrontendIndex->run()
#22 {main}
```

ggf. Zusammenhang mit #963? in einer "alten Version" von MM war das kein Problem, eine "Nicht-Auswahl" zu treffen

**Comment by xantippe** [comment]
m.E. wäre eine Lösung in
https://github.com/MetaModels/core/blob/master/src/MetaModels/Filter/Rules/SimpleQuery.php#L86
die Abfrage, ob der Parameter gesetzt ist

```diff
    public function getMatchingIds()
    {
+       if (count($this->arrParams) == 0)
+       {
+            return array();
+       }
        $objMatches = $this->dataBase
            ->prepare($this->strQueryString)
            ->execute($this->arrParams);
        return ($objMatches->numRows == 0) ? array() : $objMatches->fetchEach($this->strIdColumn);
    }
```

**Comment by xantippe** [comment]
@discordier wie besprochen nochmal "präziesere" Angeben:

* Filterset mit
** ODER
** Einfache Abfrage mit Statischem Parameter (training)
** Eingenes SQL

![shot87](https://cloud.githubusercontent.com/assets/1045318/12626465/1a727838-c539-11e5-9b25-32893414d11d.jpg)

Eigenes SQL:

```
SELECT id FROM {{table}} 
WHERE training IN 
(SELECT id FROM mm_sv_trainings WHERE vargroup = {{param::filter?name=training&default=NULL}}
)
AND FROM_UNIXTIME(`start`) >= CURDATE()
AND published = 1
```

* CE MM-Liste

![shot88](https://cloud.githubusercontent.com/assets/1045318/12626492/3c82d45e-c539-11e5-8f7a-cf59bf35b1cb.jpg)

a) wird bei den Filtereinstellungen etwas ausgewählt, ist alles prima...

![shot89](https://cloud.githubusercontent.com/assets/1045318/12626632/ecafc332-c539-11e5-80f5-20de48b2141b.jpg)

b) wird bei den Filtereinstellungen **nichts ausgewählt**, kommt ERROR

![shot90](https://cloud.githubusercontent.com/assets/1045318/12626684/30e35690-c53a-11e5-846a-9dd4a41e46ba.jpg)

```
Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in system/modules/core/library/Contao/Database/Statement.php on line 331

#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#1 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/SimpleQuery.php(90): Contao\Database\Statement->execute(Array)
#2 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(116): MetaModels\Filter\Rules\SimpleQuery->getMatchingIds()
#3 composer/vendor/metamodels/core/src/MetaModels/Filter/Rules/Condition/ConditionOr.php(98): MetaModels\Filter\Filter->getMatchingIds()
#4 composer/vendor/metamodels/core/src/MetaModels/Filter/Filter.php(116): MetaModels\Filter\Rules\Condition\ConditionOr->getMatchingIds()
#5 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(251): MetaModels\Filter\Filter->getMatchingIds()
#6 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(725): MetaModels\MetaModel->getMatchingIds(Object(MetaModels\Filter\Filter))
#7 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(575): MetaModels\MetaModel->getCount(Object(MetaModels\Filter\Filter))
#8 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(800): MetaModels\ItemList->prepare()
#9 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(115): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#10 system/modules/core/classes/Hybrid.php(231): MetaModels\FrontendIntegration\HybridList->compile()
#11 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#12 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#13 system/modules/core/library/Contao/Controller.php(476): MetaModels\FrontendIntegration\HybridList->generate()
#14 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#15 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#16 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#17 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#18 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#20 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 index.php(20): Contao\FrontendIndex->run()
#22 {main}
```

**Comment by xantippe** [comment]
mit dem Bugfix #987 kann der Parameter auch "Leer" sein 

Test:

Einstellung Filter
![shot157](https://cloud.githubusercontent.com/assets/1045318/13666430/d2623610-e6b1-11e5-8c8a-25e0449747d2.jpg)


Einstellung Liste
![shot158](https://cloud.githubusercontent.com/assets/1045318/13666400/ab333012-e6b1-11e5-8b61-301e4850f282.jpg)

Ausgabe
![shot159](https://cloud.githubusercontent.com/assets/1045318/13666404/b1b6e71c-e6b1-11e5-91d2-586f10ae6f85.jpg)

Ob eine Ausgabe erfolgt oder nicht, kann mit der Filtereinstellung "Leeren Wert erlauben" eingestellt werden.

**Comment by xantippe** [comment]
mit https://github.com/MetaModels/core/commit/c54d60b4ff6599363c29c0cbfec3fe95d4f6cf16 gefixt
