### ISSUE TITLE
Error bei Zuweisung als Kindtabelle in MM zu bestimmten Contao-Tabellen

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#996]
## Checklist before I submit this issue report

I confirm that:
- [ ] I have tested this with the latest version available
- [ ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |5.6|                                  |
| Contao version:                     |    3.5.6  |                                  |
| MetaModels version:                 |    2.0.0 (core a9)      |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    bundle_all      |                                  |

## Issue description

Umzug von DCG https://github.com/contao-community-alliance/dc-general/issues/179

Error bei Zuweisung als Kindtabelle in MM zu bestimmten Contao-Tabellen

**Events: tl_calendar_events**

URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=calendar&id=3&table=mm_filter&pid=tl_calendar_events::9&rt=cb2a4221850095a6a10a275098497ed1&ref=96ad780d```

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '3' thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 116

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(77): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('3')
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(57): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(380): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->showAll()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```

**Events: tl_calendar**
URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=calendar&table=mm_filter&act=create&pid=tl_calendar::3&rt=cb2a4221850095a6a10a275098497ed1&ref=a52ab298```
=> o.k.

**News: tl_news**
URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=news&id=1&table=mm_filter&pid=tl_news::7&rt=cb2a4221850095a6a10a275098497ed1&ref=288b2dc0```

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '1' thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 116

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(77): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('1')
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(57): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(380): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->showAll()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('news')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```

**News: tl_news_archive**

```
http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=news&table=mm_filter&pid=tl_news_archive::1&rt=cb2a4221850095a6a10a275098497ed1&ref=53851300
```

=> o.k.

## Steps to reproduce

1. MM anlegen
2. in Eigenschaften Eingabemaske als Kind-Tabelle z.B. tl_news zuweisen
3. zu News gehen und Eingabemaske der Kindtabelle aufrufen

**Comment by zonky2** [comment]
gefixt mit https://github.com/MetaModels/core/commit/9cdae2068ecb41cfd6c38119a276cc048e926c59
